/********************************************************************************
** Form generated from reading UI file 'cprogramdistributionview.ui'
**
** Created by: Qt User Interface Compiler version 4.8.7
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_CPROGRAMDISTRIBUTIONVIEW_H
#define UI_CPROGRAMDISTRIBUTIONVIEW_H

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtGui/QApplication>
#include <QtGui/QButtonGroup>
#include <QtGui/QCheckBox>
#include <QtGui/QComboBox>
#include <QtGui/QGroupBox>
#include <QtGui/QHeaderView>
#include <QtGui/QLabel>
#include <QtGui/QPushButton>
#include <QtGui/QSlider>
#include <QtGui/QTextEdit>
#include <QtGui/QWidget>

QT_BEGIN_NAMESPACE

class Ui_CProgramdistributionView
{
public:
    QLabel *label_opencurrent;
    QSlider *m_opencurrent_slider;
    QSlider *m_firetime_slider;
    QTextEdit *m_firetime;
    QLabel *label_firetime;
    QSlider *m_unfiretime_slider;
    QLabel *label_unfiretime;
    QTextEdit *m_unfiretime;
    QComboBox *comboBox_powermode;
    QLabel *label_powerouttime;
    QCheckBox *light_detection;
    QCheckBox *CAN_communication;
    QTextEdit *m_opencurrent;
    QLabel *label_mainpower;
    QLabel *m_mainpower;
    QLabel *m_backuppower;
    QLabel *label_backuppower;
    QLabel *label_openload;
    QLabel *m_overload;
    QLabel *m_openload;
    QLabel *label_overload;
    QLabel *m_systemfault;
    QLabel *label_emergency;
    QLabel *label_systemfault;
    QLabel *m_chargestatus;
    QLabel *m_emergency;
    QLabel *m_out36v;
    QLabel *label_out36v;
    QLabel *label_chargestatus;
    QLabel *m_undervoltage;
    QLabel *m_overdischarge;
    QLabel *m_overheat;
    QLabel *label_overdischarge;
    QLabel *m_runmode;
    QLabel *label_undervoltage;
    QLabel *label_overheat;
    QLabel *label_runmodel;
    QComboBox *comboBox_linkageInput;
    QLabel *label_linkageInput;
    QLabel *label_loopoutstatus;
    QComboBox *comboBox_loopoutstatus;
    QPushButton *readloopoutstatus_button;
    QPushButton *closepowerout_button;
    QPushButton *poweroutkeep_button;
    QLabel *label_productID;
    QTextEdit *m_productID;
    QPushButton *emergencyStart_button;
    QPushButton *emergencyStop_button;
    QGroupBox *groupBox_loopcommunication;
    QLabel *m_loopc7;
    QLabel *m_loopc4;
    QLabel *m_loopc3;
    QLabel *m_loopc5;
    QLabel *m_loopc8;
    QLabel *m_loopc6;
    QLabel *m_loopc2;
    QLabel *m_loopc1;
    QGroupBox *groupBox_loopopen;
    QLabel *m_loopo8;
    QLabel *m_loopo5;
    QLabel *m_loopo3;
    QLabel *m_loopo2;
    QLabel *m_loopo7;
    QLabel *m_loopo6;
    QLabel *m_loopo4;
    QLabel *m_loopo1;
    QPushButton *removeLampLogin_button;

    void setupUi(QWidget *CProgramdistributionView)
    {
        if (CProgramdistributionView->objectName().isEmpty())
            CProgramdistributionView->setObjectName(QString::fromUtf8("CProgramdistributionView"));
        CProgramdistributionView->resize(1046, 490);
        CProgramdistributionView->setMaximumSize(QSize(1046, 626));
        QFont font;
        font.setPointSize(12);
        CProgramdistributionView->setFont(font);
        CProgramdistributionView->setContextMenuPolicy(Qt::DefaultContextMenu);
        CProgramdistributionView->setWindowTitle(QString::fromUtf8("Form"));
        CProgramdistributionView->setLayoutDirection(Qt::LeftToRight);
        label_opencurrent = new QLabel(CProgramdistributionView);
        label_opencurrent->setObjectName(QString::fromUtf8("label_opencurrent"));
        label_opencurrent->setGeometry(QRect(690, 12, 120, 30));
        label_opencurrent->setFont(font);
        m_opencurrent_slider = new QSlider(CProgramdistributionView);
        m_opencurrent_slider->setObjectName(QString::fromUtf8("m_opencurrent_slider"));
        m_opencurrent_slider->setGeometry(QRect(880, 12, 70, 30));
        m_opencurrent_slider->setMaximumSize(QSize(70, 30));
        m_opencurrent_slider->setFont(font);
        m_opencurrent_slider->setMaximum(10);
        m_opencurrent_slider->setOrientation(Qt::Horizontal);
        m_firetime_slider = new QSlider(CProgramdistributionView);
        m_firetime_slider->setObjectName(QString::fromUtf8("m_firetime_slider"));
        m_firetime_slider->setGeometry(QRect(260, 12, 70, 30));
        m_firetime_slider->setMaximumSize(QSize(70, 30));
        m_firetime_slider->setFont(font);
        m_firetime_slider->setMinimum(30);
        m_firetime_slider->setMaximum(240);
        m_firetime_slider->setValue(100);
        m_firetime_slider->setOrientation(Qt::Horizontal);
        m_firetime = new QTextEdit(CProgramdistributionView);
        m_firetime->setObjectName(QString::fromUtf8("m_firetime"));
        m_firetime->setGeometry(QRect(200, 10, 50, 35));
        m_firetime->setMinimumSize(QSize(50, 35));
        m_firetime->setMaximumSize(QSize(50, 35));
        m_firetime->setFont(font);
        m_firetime->setReadOnly(true);
        label_firetime = new QLabel(CProgramdistributionView);
        label_firetime->setObjectName(QString::fromUtf8("label_firetime"));
        label_firetime->setGeometry(QRect(90, 12, 100, 30));
        label_firetime->setFont(font);
        m_unfiretime_slider = new QSlider(CProgramdistributionView);
        m_unfiretime_slider->setObjectName(QString::fromUtf8("m_unfiretime_slider"));
        m_unfiretime_slider->setGeometry(QRect(570, 12, 70, 30));
        m_unfiretime_slider->setMaximumSize(QSize(70, 30));
        m_unfiretime_slider->setFont(font);
        m_unfiretime_slider->setMinimum(30);
        m_unfiretime_slider->setMaximum(240);
        m_unfiretime_slider->setOrientation(Qt::Horizontal);
        label_unfiretime = new QLabel(CProgramdistributionView);
        label_unfiretime->setObjectName(QString::fromUtf8("label_unfiretime"));
        label_unfiretime->setGeometry(QRect(380, 12, 120, 30));
        label_unfiretime->setFont(font);
        m_unfiretime = new QTextEdit(CProgramdistributionView);
        m_unfiretime->setObjectName(QString::fromUtf8("m_unfiretime"));
        m_unfiretime->setGeometry(QRect(510, 10, 50, 35));
        m_unfiretime->setMinimumSize(QSize(50, 35));
        m_unfiretime->setMaximumSize(QSize(50, 35));
        m_unfiretime->setFont(font);
        m_unfiretime->setReadOnly(true);
        comboBox_powermode = new QComboBox(CProgramdistributionView);
        comboBox_powermode->setObjectName(QString::fromUtf8("comboBox_powermode"));
        comboBox_powermode->setGeometry(QRect(200, 105, 120, 30));
        QFont font1;
        font1.setPointSize(13);
        comboBox_powermode->setFont(font1);
        label_powerouttime = new QLabel(CProgramdistributionView);
        label_powerouttime->setObjectName(QString::fromUtf8("label_powerouttime"));
        label_powerouttime->setGeometry(QRect(80, 105, 110, 30));
        label_powerouttime->setFont(font);
        light_detection = new QCheckBox(CProgramdistributionView);
        light_detection->setObjectName(QString::fromUtf8("light_detection"));
        light_detection->setGeometry(QRect(70, 60, 130, 30));
        light_detection->setFont(font);
        CAN_communication = new QCheckBox(CProgramdistributionView);
        CAN_communication->setObjectName(QString::fromUtf8("CAN_communication"));
        CAN_communication->setGeometry(QRect(220, 60, 130, 30));
        CAN_communication->setFont(font);
        m_opencurrent = new QTextEdit(CProgramdistributionView);
        m_opencurrent->setObjectName(QString::fromUtf8("m_opencurrent"));
        m_opencurrent->setGeometry(QRect(820, 10, 50, 35));
        m_opencurrent->setMinimumSize(QSize(50, 35));
        m_opencurrent->setMaximumSize(QSize(50, 35));
        m_opencurrent->setFont(font);
        m_opencurrent->setReadOnly(true);
        label_mainpower = new QLabel(CProgramdistributionView);
        label_mainpower->setObjectName(QString::fromUtf8("label_mainpower"));
        label_mainpower->setGeometry(QRect(70, 220, 70, 25));
        label_mainpower->setFont(font);
        label_mainpower->setAlignment(Qt::AlignCenter);
        m_mainpower = new QLabel(CProgramdistributionView);
        m_mainpower->setObjectName(QString::fromUtf8("m_mainpower"));
        m_mainpower->setGeometry(QRect(150, 220, 50, 25));
        m_mainpower->setFont(font);
        m_mainpower->setStyleSheet(QString::fromUtf8("background-color: rgb(0,255,0);"));
        m_mainpower->setAlignment(Qt::AlignCenter);
        m_backuppower = new QLabel(CProgramdistributionView);
        m_backuppower->setObjectName(QString::fromUtf8("m_backuppower"));
        m_backuppower->setGeometry(QRect(300, 220, 50, 25));
        m_backuppower->setFont(font);
        m_backuppower->setStyleSheet(QString::fromUtf8("background-color: rgb(0,255,0);"));
        m_backuppower->setAlignment(Qt::AlignCenter);
        label_backuppower = new QLabel(CProgramdistributionView);
        label_backuppower->setObjectName(QString::fromUtf8("label_backuppower"));
        label_backuppower->setGeometry(QRect(220, 220, 70, 25));
        label_backuppower->setFont(font);
        label_backuppower->setAlignment(Qt::AlignCenter);
        label_openload = new QLabel(CProgramdistributionView);
        label_openload->setObjectName(QString::fromUtf8("label_openload"));
        label_openload->setGeometry(QRect(520, 220, 70, 25));
        label_openload->setFont(font);
        label_openload->setAlignment(Qt::AlignCenter);
        m_overload = new QLabel(CProgramdistributionView);
        m_overload->setObjectName(QString::fromUtf8("m_overload"));
        m_overload->setGeometry(QRect(450, 220, 50, 25));
        m_overload->setFont(font);
        m_overload->setStyleSheet(QString::fromUtf8("background-color: rgb(0,255,0);"));
        m_overload->setAlignment(Qt::AlignCenter);
        m_openload = new QLabel(CProgramdistributionView);
        m_openload->setObjectName(QString::fromUtf8("m_openload"));
        m_openload->setGeometry(QRect(600, 220, 50, 25));
        m_openload->setFont(font);
        m_openload->setStyleSheet(QString::fromUtf8("background-color: rgb(0,255,0);"));
        m_openload->setAlignment(Qt::AlignCenter);
        label_overload = new QLabel(CProgramdistributionView);
        label_overload->setObjectName(QString::fromUtf8("label_overload"));
        label_overload->setGeometry(QRect(370, 220, 70, 25));
        label_overload->setFont(font);
        label_overload->setAlignment(Qt::AlignCenter);
        m_systemfault = new QLabel(CProgramdistributionView);
        m_systemfault->setObjectName(QString::fromUtf8("m_systemfault"));
        m_systemfault->setGeometry(QRect(300, 270, 50, 25));
        m_systemfault->setFont(font);
        m_systemfault->setStyleSheet(QString::fromUtf8("background-color: rgb(0,255,0);"));
        m_systemfault->setAlignment(Qt::AlignCenter);
        label_emergency = new QLabel(CProgramdistributionView);
        label_emergency->setObjectName(QString::fromUtf8("label_emergency"));
        label_emergency->setGeometry(QRect(820, 220, 70, 25));
        label_emergency->setFont(font);
        label_emergency->setAlignment(Qt::AlignCenter);
        label_systemfault = new QLabel(CProgramdistributionView);
        label_systemfault->setObjectName(QString::fromUtf8("label_systemfault"));
        label_systemfault->setGeometry(QRect(220, 270, 70, 25));
        label_systemfault->setFont(font);
        label_systemfault->setAlignment(Qt::AlignCenter);
        m_chargestatus = new QLabel(CProgramdistributionView);
        m_chargestatus->setObjectName(QString::fromUtf8("m_chargestatus"));
        m_chargestatus->setGeometry(QRect(750, 220, 50, 25));
        m_chargestatus->setFont(font);
        m_chargestatus->setStyleSheet(QString::fromUtf8("background-color: rgb(0,255,0);"));
        m_chargestatus->setAlignment(Qt::AlignCenter);
        m_emergency = new QLabel(CProgramdistributionView);
        m_emergency->setObjectName(QString::fromUtf8("m_emergency"));
        m_emergency->setGeometry(QRect(900, 220, 50, 25));
        m_emergency->setFont(font);
        m_emergency->setStyleSheet(QString::fromUtf8("background-color: rgb(0,255,0);"));
        m_emergency->setAlignment(Qt::AlignCenter);
        m_out36v = new QLabel(CProgramdistributionView);
        m_out36v->setObjectName(QString::fromUtf8("m_out36v"));
        m_out36v->setGeometry(QRect(150, 270, 50, 25));
        m_out36v->setFont(font);
        m_out36v->setStyleSheet(QString::fromUtf8("background-color: rgb(0,255,0);"));
        m_out36v->setAlignment(Qt::AlignCenter);
        label_out36v = new QLabel(CProgramdistributionView);
        label_out36v->setObjectName(QString::fromUtf8("label_out36v"));
        label_out36v->setGeometry(QRect(70, 270, 70, 25));
        label_out36v->setFont(font);
        label_out36v->setAlignment(Qt::AlignCenter);
        label_chargestatus = new QLabel(CProgramdistributionView);
        label_chargestatus->setObjectName(QString::fromUtf8("label_chargestatus"));
        label_chargestatus->setGeometry(QRect(670, 220, 70, 25));
        label_chargestatus->setFont(font);
        label_chargestatus->setAlignment(Qt::AlignCenter);
        m_undervoltage = new QLabel(CProgramdistributionView);
        m_undervoltage->setObjectName(QString::fromUtf8("m_undervoltage"));
        m_undervoltage->setGeometry(QRect(750, 270, 50, 25));
        m_undervoltage->setFont(font);
        m_undervoltage->setStyleSheet(QString::fromUtf8("background-color: rgb(0,255,0);"));
        m_undervoltage->setAlignment(Qt::AlignCenter);
        m_overdischarge = new QLabel(CProgramdistributionView);
        m_overdischarge->setObjectName(QString::fromUtf8("m_overdischarge"));
        m_overdischarge->setGeometry(QRect(600, 270, 50, 25));
        m_overdischarge->setFont(font);
        m_overdischarge->setStyleSheet(QString::fromUtf8("background-color: rgb(0,255,0);"));
        m_overdischarge->setAlignment(Qt::AlignCenter);
        m_overheat = new QLabel(CProgramdistributionView);
        m_overheat->setObjectName(QString::fromUtf8("m_overheat"));
        m_overheat->setGeometry(QRect(900, 270, 50, 25));
        m_overheat->setFont(font);
        m_overheat->setStyleSheet(QString::fromUtf8("background-color: rgb(0,255,0);"));
        m_overheat->setAlignment(Qt::AlignCenter);
        label_overdischarge = new QLabel(CProgramdistributionView);
        label_overdischarge->setObjectName(QString::fromUtf8("label_overdischarge"));
        label_overdischarge->setGeometry(QRect(520, 270, 70, 25));
        label_overdischarge->setFont(font);
        label_overdischarge->setAlignment(Qt::AlignCenter);
        m_runmode = new QLabel(CProgramdistributionView);
        m_runmode->setObjectName(QString::fromUtf8("m_runmode"));
        m_runmode->setGeometry(QRect(450, 270, 50, 25));
        m_runmode->setFont(font);
        m_runmode->setStyleSheet(QString::fromUtf8("background-color: rgb(0,255,0);"));
        m_runmode->setAlignment(Qt::AlignCenter);
        label_undervoltage = new QLabel(CProgramdistributionView);
        label_undervoltage->setObjectName(QString::fromUtf8("label_undervoltage"));
        label_undervoltage->setGeometry(QRect(670, 270, 70, 25));
        label_undervoltage->setFont(font);
        label_undervoltage->setAlignment(Qt::AlignCenter);
        label_overheat = new QLabel(CProgramdistributionView);
        label_overheat->setObjectName(QString::fromUtf8("label_overheat"));
        label_overheat->setGeometry(QRect(820, 270, 70, 25));
        label_overheat->setFont(font);
        label_overheat->setAlignment(Qt::AlignCenter);
        label_runmodel = new QLabel(CProgramdistributionView);
        label_runmodel->setObjectName(QString::fromUtf8("label_runmodel"));
        label_runmodel->setGeometry(QRect(370, 270, 70, 25));
        label_runmodel->setFont(font);
        label_runmodel->setAlignment(Qt::AlignCenter);
        comboBox_linkageInput = new QComboBox(CProgramdistributionView);
        comboBox_linkageInput->setObjectName(QString::fromUtf8("comboBox_linkageInput"));
        comboBox_linkageInput->setGeometry(QRect(470, 105, 120, 30));
        comboBox_linkageInput->setFont(font1);
        label_linkageInput = new QLabel(CProgramdistributionView);
        label_linkageInput->setObjectName(QString::fromUtf8("label_linkageInput"));
        label_linkageInput->setGeometry(QRect(360, 105, 110, 30));
        label_linkageInput->setFont(font);
        label_loopoutstatus = new QLabel(CProgramdistributionView);
        label_loopoutstatus->setObjectName(QString::fromUtf8("label_loopoutstatus"));
        label_loopoutstatus->setGeometry(QRect(140, 160, 160, 30));
        label_loopoutstatus->setFont(font);
        comboBox_loopoutstatus = new QComboBox(CProgramdistributionView);
        comboBox_loopoutstatus->setObjectName(QString::fromUtf8("comboBox_loopoutstatus"));
        comboBox_loopoutstatus->setGeometry(QRect(390, 160, 140, 30));
        comboBox_loopoutstatus->setFont(font1);
        readloopoutstatus_button = new QPushButton(CProgramdistributionView);
        readloopoutstatus_button->setObjectName(QString::fromUtf8("readloopoutstatus_button"));
        readloopoutstatus_button->setGeometry(QRect(310, 160, 60, 30));
        readloopoutstatus_button->setMinimumSize(QSize(60, 30));
        readloopoutstatus_button->setFont(font);
        closepowerout_button = new QPushButton(CProgramdistributionView);
        closepowerout_button->setObjectName(QString::fromUtf8("closepowerout_button"));
        closepowerout_button->setGeometry(QRect(620, 160, 120, 30));
        closepowerout_button->setMinimumSize(QSize(60, 30));
        closepowerout_button->setFont(font);
        poweroutkeep_button = new QPushButton(CProgramdistributionView);
        poweroutkeep_button->setObjectName(QString::fromUtf8("poweroutkeep_button"));
        poweroutkeep_button->setGeometry(QRect(770, 160, 120, 30));
        poweroutkeep_button->setMinimumSize(QSize(60, 30));
        poweroutkeep_button->setFont(font);
        label_productID = new QLabel(CProgramdistributionView);
        label_productID->setObjectName(QString::fromUtf8("label_productID"));
        label_productID->setGeometry(QRect(380, 60, 150, 30));
        label_productID->setFont(font);
        m_productID = new QTextEdit(CProgramdistributionView);
        m_productID->setObjectName(QString::fromUtf8("m_productID"));
        m_productID->setGeometry(QRect(520, 55, 190, 35));
        QSizePolicy sizePolicy(QSizePolicy::Minimum, QSizePolicy::Expanding);
        sizePolicy.setHorizontalStretch(0);
        sizePolicy.setVerticalStretch(0);
        sizePolicy.setHeightForWidth(m_productID->sizePolicy().hasHeightForWidth());
        m_productID->setSizePolicy(sizePolicy);
        m_productID->setMinimumSize(QSize(190, 35));
        m_productID->setMaximumSize(QSize(190, 35));
        m_productID->setFont(font);
        m_productID->setReadOnly(true);
        emergencyStart_button = new QPushButton(CProgramdistributionView);
        emergencyStart_button->setObjectName(QString::fromUtf8("emergencyStart_button"));
        emergencyStart_button->setGeometry(QRect(680, 110, 90, 30));
        emergencyStart_button->setMinimumSize(QSize(60, 30));
        emergencyStart_button->setFont(font);
        emergencyStop_button = new QPushButton(CProgramdistributionView);
        emergencyStop_button->setObjectName(QString::fromUtf8("emergencyStop_button"));
        emergencyStop_button->setGeometry(QRect(840, 110, 90, 30));
        emergencyStop_button->setMinimumSize(QSize(60, 30));
        emergencyStop_button->setFont(font);
        groupBox_loopcommunication = new QGroupBox(CProgramdistributionView);
        groupBox_loopcommunication->setObjectName(QString::fromUtf8("groupBox_loopcommunication"));
        groupBox_loopcommunication->setGeometry(QRect(170, 320, 300, 100));
        groupBox_loopcommunication->setFont(font);
        m_loopc7 = new QLabel(groupBox_loopcommunication);
        m_loopc7->setObjectName(QString::fromUtf8("m_loopc7"));
        m_loopc7->setGeometry(QRect(170, 65, 40, 25));
        m_loopc7->setFont(font);
        m_loopc7->setLayoutDirection(Qt::LeftToRight);
        m_loopc7->setStyleSheet(QString::fromUtf8("background-color: rgb(0,255,0);"));
        m_loopc7->setAlignment(Qt::AlignCenter);
        m_loopc4 = new QLabel(groupBox_loopcommunication);
        m_loopc4->setObjectName(QString::fromUtf8("m_loopc4"));
        m_loopc4->setGeometry(QRect(250, 30, 40, 25));
        m_loopc4->setFont(font);
        m_loopc4->setLayoutDirection(Qt::LeftToRight);
        m_loopc4->setStyleSheet(QString::fromUtf8("background-color: rgb(0,255,0);"));
        m_loopc4->setAlignment(Qt::AlignCenter);
        m_loopc3 = new QLabel(groupBox_loopcommunication);
        m_loopc3->setObjectName(QString::fromUtf8("m_loopc3"));
        m_loopc3->setGeometry(QRect(170, 30, 40, 25));
        m_loopc3->setFont(font);
        m_loopc3->setLayoutDirection(Qt::LeftToRight);
        m_loopc3->setStyleSheet(QString::fromUtf8("background-color: rgb(0,255,0);"));
        m_loopc3->setAlignment(Qt::AlignCenter);
        m_loopc5 = new QLabel(groupBox_loopcommunication);
        m_loopc5->setObjectName(QString::fromUtf8("m_loopc5"));
        m_loopc5->setGeometry(QRect(10, 65, 40, 25));
        m_loopc5->setFont(font);
        m_loopc5->setLayoutDirection(Qt::LeftToRight);
        m_loopc5->setStyleSheet(QString::fromUtf8("background-color: rgb(0,255,0);"));
        m_loopc5->setAlignment(Qt::AlignCenter);
        m_loopc8 = new QLabel(groupBox_loopcommunication);
        m_loopc8->setObjectName(QString::fromUtf8("m_loopc8"));
        m_loopc8->setGeometry(QRect(250, 65, 40, 25));
        m_loopc8->setFont(font);
        m_loopc8->setLayoutDirection(Qt::LeftToRight);
        m_loopc8->setStyleSheet(QString::fromUtf8("background-color: rgb(0,255,0);"));
        m_loopc8->setAlignment(Qt::AlignCenter);
        m_loopc6 = new QLabel(groupBox_loopcommunication);
        m_loopc6->setObjectName(QString::fromUtf8("m_loopc6"));
        m_loopc6->setGeometry(QRect(90, 65, 40, 25));
        m_loopc6->setFont(font);
        m_loopc6->setLayoutDirection(Qt::LeftToRight);
        m_loopc6->setStyleSheet(QString::fromUtf8("background-color: rgb(0,255,0);"));
        m_loopc6->setAlignment(Qt::AlignCenter);
        m_loopc2 = new QLabel(groupBox_loopcommunication);
        m_loopc2->setObjectName(QString::fromUtf8("m_loopc2"));
        m_loopc2->setGeometry(QRect(90, 30, 40, 25));
        m_loopc2->setFont(font);
        m_loopc2->setLayoutDirection(Qt::LeftToRight);
        m_loopc2->setStyleSheet(QString::fromUtf8("background-color: rgb(0,255,0);"));
        m_loopc2->setAlignment(Qt::AlignCenter);
        m_loopc1 = new QLabel(groupBox_loopcommunication);
        m_loopc1->setObjectName(QString::fromUtf8("m_loopc1"));
        m_loopc1->setGeometry(QRect(10, 30, 40, 25));
        m_loopc1->setFont(font);
        m_loopc1->setLayoutDirection(Qt::LeftToRight);
        m_loopc1->setStyleSheet(QString::fromUtf8("background-color: rgb(0,255,0);"));
        m_loopc1->setAlignment(Qt::AlignCenter);
        groupBox_loopopen = new QGroupBox(CProgramdistributionView);
        groupBox_loopopen->setObjectName(QString::fromUtf8("groupBox_loopopen"));
        groupBox_loopopen->setGeometry(QRect(590, 320, 300, 100));
        groupBox_loopopen->setFont(font);
        m_loopo8 = new QLabel(groupBox_loopopen);
        m_loopo8->setObjectName(QString::fromUtf8("m_loopo8"));
        m_loopo8->setGeometry(QRect(250, 65, 40, 25));
        m_loopo8->setFont(font);
        m_loopo8->setLayoutDirection(Qt::LeftToRight);
        m_loopo8->setStyleSheet(QString::fromUtf8("background-color: rgb(0,255,0);"));
        m_loopo8->setAlignment(Qt::AlignCenter);
        m_loopo5 = new QLabel(groupBox_loopopen);
        m_loopo5->setObjectName(QString::fromUtf8("m_loopo5"));
        m_loopo5->setGeometry(QRect(10, 65, 40, 25));
        m_loopo5->setFont(font);
        m_loopo5->setLayoutDirection(Qt::LeftToRight);
        m_loopo5->setStyleSheet(QString::fromUtf8("background-color: rgb(0,255,0);"));
        m_loopo5->setAlignment(Qt::AlignCenter);
        m_loopo3 = new QLabel(groupBox_loopopen);
        m_loopo3->setObjectName(QString::fromUtf8("m_loopo3"));
        m_loopo3->setGeometry(QRect(170, 30, 40, 25));
        m_loopo3->setFont(font);
        m_loopo3->setLayoutDirection(Qt::LeftToRight);
        m_loopo3->setStyleSheet(QString::fromUtf8("background-color: rgb(0,255,0);"));
        m_loopo3->setAlignment(Qt::AlignCenter);
        m_loopo2 = new QLabel(groupBox_loopopen);
        m_loopo2->setObjectName(QString::fromUtf8("m_loopo2"));
        m_loopo2->setGeometry(QRect(90, 30, 40, 25));
        m_loopo2->setFont(font);
        m_loopo2->setLayoutDirection(Qt::LeftToRight);
        m_loopo2->setStyleSheet(QString::fromUtf8("background-color: rgb(0,255,0);"));
        m_loopo2->setAlignment(Qt::AlignCenter);
        m_loopo7 = new QLabel(groupBox_loopopen);
        m_loopo7->setObjectName(QString::fromUtf8("m_loopo7"));
        m_loopo7->setGeometry(QRect(170, 65, 40, 25));
        m_loopo7->setFont(font);
        m_loopo7->setLayoutDirection(Qt::LeftToRight);
        m_loopo7->setStyleSheet(QString::fromUtf8("background-color: rgb(0,255,0);"));
        m_loopo7->setAlignment(Qt::AlignCenter);
        m_loopo6 = new QLabel(groupBox_loopopen);
        m_loopo6->setObjectName(QString::fromUtf8("m_loopo6"));
        m_loopo6->setGeometry(QRect(90, 65, 40, 25));
        m_loopo6->setFont(font);
        m_loopo6->setLayoutDirection(Qt::LeftToRight);
        m_loopo6->setStyleSheet(QString::fromUtf8("background-color: rgb(0,255,0);"));
        m_loopo6->setAlignment(Qt::AlignCenter);
        m_loopo4 = new QLabel(groupBox_loopopen);
        m_loopo4->setObjectName(QString::fromUtf8("m_loopo4"));
        m_loopo4->setGeometry(QRect(250, 30, 40, 25));
        m_loopo4->setFont(font);
        m_loopo4->setLayoutDirection(Qt::LeftToRight);
        m_loopo4->setStyleSheet(QString::fromUtf8("background-color: rgb(0,255,0);"));
        m_loopo4->setAlignment(Qt::AlignCenter);
        m_loopo1 = new QLabel(groupBox_loopopen);
        m_loopo1->setObjectName(QString::fromUtf8("m_loopo1"));
        m_loopo1->setGeometry(QRect(10, 30, 40, 25));
        m_loopo1->setFont(font);
        m_loopo1->setLayoutDirection(Qt::LeftToRight);
        m_loopo1->setStyleSheet(QString::fromUtf8("background-color: rgb(0,255,0);"));
        m_loopo1->setAlignment(Qt::AlignCenter);
        removeLampLogin_button = new QPushButton(CProgramdistributionView);
        removeLampLogin_button->setObjectName(QString::fromUtf8("removeLampLogin_button"));
        removeLampLogin_button->setGeometry(QRect(760, 60, 171, 30));
        removeLampLogin_button->setMinimumSize(QSize(60, 30));
        removeLampLogin_button->setFont(font);
        label_opencurrent->raise();
        m_opencurrent_slider->raise();
        m_firetime_slider->raise();
        m_firetime->raise();
        label_firetime->raise();
        m_opencurrent->raise();
        m_unfiretime_slider->raise();
        label_unfiretime->raise();
        m_unfiretime->raise();
        comboBox_powermode->raise();
        label_powerouttime->raise();
        light_detection->raise();
        CAN_communication->raise();
        label_mainpower->raise();
        m_mainpower->raise();
        m_backuppower->raise();
        label_backuppower->raise();
        label_openload->raise();
        m_overload->raise();
        m_openload->raise();
        label_overload->raise();
        m_systemfault->raise();
        label_emergency->raise();
        label_systemfault->raise();
        m_chargestatus->raise();
        m_emergency->raise();
        m_out36v->raise();
        label_out36v->raise();
        label_chargestatus->raise();
        m_undervoltage->raise();
        m_overdischarge->raise();
        m_overheat->raise();
        label_overdischarge->raise();
        m_runmode->raise();
        label_undervoltage->raise();
        label_overheat->raise();
        label_runmodel->raise();
        comboBox_linkageInput->raise();
        label_linkageInput->raise();
        label_loopoutstatus->raise();
        comboBox_loopoutstatus->raise();
        readloopoutstatus_button->raise();
        closepowerout_button->raise();
        poweroutkeep_button->raise();
        label_productID->raise();
        m_productID->raise();
        emergencyStart_button->raise();
        emergencyStop_button->raise();
        groupBox_loopcommunication->raise();
        groupBox_loopopen->raise();
        removeLampLogin_button->raise();

        retranslateUi(CProgramdistributionView);

        comboBox_powermode->setCurrentIndex(-1);
        comboBox_loopoutstatus->setCurrentIndex(-1);


        QMetaObject::connectSlotsByName(CProgramdistributionView);
    } // setupUi

    void retranslateUi(QWidget *CProgramdistributionView)
    {
        label_opencurrent->setText(QApplication::translate("CProgramdistributionView", "\345\274\200\350\267\257\347\224\265\346\265\201(0.1A):", 0, QApplication::UnicodeUTF8));
        label_firetime->setText(QApplication::translate("CProgramdistributionView", "\347\201\253\347\201\276\345\272\224\346\200\245\346\227\266\351\227\264:", 0, QApplication::UnicodeUTF8));
        label_unfiretime->setText(QApplication::translate("CProgramdistributionView", "\351\235\236\347\201\253\347\201\276\345\272\224\346\200\245\346\227\266\351\227\264:", 0, QApplication::UnicodeUTF8));
        label_powerouttime->setText(QApplication::translate("CProgramdistributionView", "\347\224\265\346\272\220\350\276\223\345\207\272\346\250\241\345\274\217:", 0, QApplication::UnicodeUTF8));
        light_detection->setText(QApplication::translate("CProgramdistributionView", "\347\205\247\346\230\216\346\243\200\346\265\213\345\274\200\345\205\263", 0, QApplication::UnicodeUTF8));
        CAN_communication->setText(QApplication::translate("CProgramdistributionView", "CAN\351\200\232\350\256\257\346\225\205\351\232\234", 0, QApplication::UnicodeUTF8));
        label_mainpower->setText(QApplication::translate("CProgramdistributionView", "\344\270\273\347\224\265:", 0, QApplication::UnicodeUTF8));
        m_mainpower->setText(QApplication::translate("CProgramdistributionView", "\346\255\243\345\270\270", 0, QApplication::UnicodeUTF8));
        m_backuppower->setText(QApplication::translate("CProgramdistributionView", "\346\255\243\345\270\270", 0, QApplication::UnicodeUTF8));
        label_backuppower->setText(QApplication::translate("CProgramdistributionView", "\345\244\207\347\224\265:", 0, QApplication::UnicodeUTF8));
        label_openload->setText(QApplication::translate("CProgramdistributionView", "\350\276\223\345\207\272\345\274\200\350\267\257:", 0, QApplication::UnicodeUTF8));
        m_overload->setText(QApplication::translate("CProgramdistributionView", "\346\255\243\345\270\270", 0, QApplication::UnicodeUTF8));
        m_openload->setText(QApplication::translate("CProgramdistributionView", "\346\255\243\345\270\270", 0, QApplication::UnicodeUTF8));
        label_overload->setText(QApplication::translate("CProgramdistributionView", "\350\276\223\345\207\272\350\277\207\350\275\275:", 0, QApplication::UnicodeUTF8));
        m_systemfault->setText(QApplication::translate("CProgramdistributionView", "\346\255\243\345\270\270", 0, QApplication::UnicodeUTF8));
        label_emergency->setText(QApplication::translate("CProgramdistributionView", "\345\272\224\346\200\245:", 0, QApplication::UnicodeUTF8));
        label_systemfault->setText(QApplication::translate("CProgramdistributionView", "\347\263\273\347\273\237\346\225\205\351\232\234:", 0, QApplication::UnicodeUTF8));
        m_chargestatus->setText(QApplication::translate("CProgramdistributionView", "\346\234\252\345\205\205\347\224\265", 0, QApplication::UnicodeUTF8));
        m_emergency->setText(QApplication::translate("CProgramdistributionView", "\346\255\243\345\270\270", 0, QApplication::UnicodeUTF8));
        m_out36v->setText(QApplication::translate("CProgramdistributionView", "\346\255\243\345\270\270", 0, QApplication::UnicodeUTF8));
        label_out36v->setText(QApplication::translate("CProgramdistributionView", "36V\350\276\223\345\207\272:", 0, QApplication::UnicodeUTF8));
        label_chargestatus->setText(QApplication::translate("CProgramdistributionView", "\345\205\205\347\224\265\347\212\266\346\200\201:", 0, QApplication::UnicodeUTF8));
        m_undervoltage->setText(QApplication::translate("CProgramdistributionView", "\346\255\243\345\270\270", 0, QApplication::UnicodeUTF8));
        m_overdischarge->setText(QApplication::translate("CProgramdistributionView", "\346\255\243\345\270\270", 0, QApplication::UnicodeUTF8));
        m_overheat->setText(QApplication::translate("CProgramdistributionView", "\346\255\243\345\270\270", 0, QApplication::UnicodeUTF8));
        label_overdischarge->setText(QApplication::translate("CProgramdistributionView", "\350\277\207\346\224\276\347\224\265:", 0, QApplication::UnicodeUTF8));
        m_runmode->setText(QApplication::translate("CProgramdistributionView", "\350\207\252\345\212\250", 0, QApplication::UnicodeUTF8));
        label_undervoltage->setText(QApplication::translate("CProgramdistributionView", "\347\224\265\346\261\240\346\254\240\345\216\213:", 0, QApplication::UnicodeUTF8));
        label_overheat->setText(QApplication::translate("CProgramdistributionView", "\347\224\265\346\261\240\350\277\207\347\203\255:", 0, QApplication::UnicodeUTF8));
        label_runmodel->setText(QApplication::translate("CProgramdistributionView", "\350\277\220\350\241\214\346\250\241\345\274\217:", 0, QApplication::UnicodeUTF8));
        label_linkageInput->setText(QApplication::translate("CProgramdistributionView", "\350\201\224\345\212\250\350\276\223\345\205\245\345\274\200\345\205\263:", 0, QApplication::UnicodeUTF8));
        label_loopoutstatus->setText(QApplication::translate("CProgramdistributionView", "\351\205\215\347\224\265\347\256\261\345\272\224\346\200\245\345\233\236\350\267\257\347\212\266\346\200\201:", 0, QApplication::UnicodeUTF8));
        readloopoutstatus_button->setText(QApplication::translate("CProgramdistributionView", "\350\257\273\345\217\226", 0, QApplication::UnicodeUTF8));
        closepowerout_button->setText(QApplication::translate("CProgramdistributionView", "\345\205\263\351\227\255\347\224\265\346\261\240\350\276\223\345\207\272", 0, QApplication::UnicodeUTF8));
        poweroutkeep_button->setText(QApplication::translate("CProgramdistributionView", "\347\224\265\346\261\240\350\276\223\345\207\272\344\277\235\346\214\201", 0, QApplication::UnicodeUTF8));
        label_productID->setText(QApplication::translate("CProgramdistributionView", "\344\272\247\345\223\201\347\274\226\345\217\267(\345\224\257\344\270\200\347\240\201):", 0, QApplication::UnicodeUTF8));
        emergencyStart_button->setText(QApplication::translate("CProgramdistributionView", "\345\272\224\346\200\245\345\220\257\345\212\250", 0, QApplication::UnicodeUTF8));
        emergencyStop_button->setText(QApplication::translate("CProgramdistributionView", "\345\272\224\346\200\245\345\201\234\346\255\242", 0, QApplication::UnicodeUTF8));
        groupBox_loopcommunication->setTitle(QApplication::translate("CProgramdistributionView", "\345\233\236\350\267\257\351\200\232\350\256\257", 0, QApplication::UnicodeUTF8));
        m_loopc7->setText(QApplication::translate("CProgramdistributionView", "7", 0, QApplication::UnicodeUTF8));
        m_loopc4->setText(QApplication::translate("CProgramdistributionView", "4", 0, QApplication::UnicodeUTF8));
        m_loopc3->setText(QApplication::translate("CProgramdistributionView", "3", 0, QApplication::UnicodeUTF8));
        m_loopc5->setText(QApplication::translate("CProgramdistributionView", "5", 0, QApplication::UnicodeUTF8));
        m_loopc8->setText(QApplication::translate("CProgramdistributionView", "8", 0, QApplication::UnicodeUTF8));
        m_loopc6->setText(QApplication::translate("CProgramdistributionView", "6", 0, QApplication::UnicodeUTF8));
        m_loopc2->setText(QApplication::translate("CProgramdistributionView", "2", 0, QApplication::UnicodeUTF8));
        m_loopc1->setText(QApplication::translate("CProgramdistributionView", "1", 0, QApplication::UnicodeUTF8));
        groupBox_loopopen->setTitle(QApplication::translate("CProgramdistributionView", "\345\233\236\350\267\257\345\274\200\350\267\257", 0, QApplication::UnicodeUTF8));
        m_loopo8->setText(QApplication::translate("CProgramdistributionView", "8", 0, QApplication::UnicodeUTF8));
        m_loopo5->setText(QApplication::translate("CProgramdistributionView", "5", 0, QApplication::UnicodeUTF8));
        m_loopo3->setText(QApplication::translate("CProgramdistributionView", "3", 0, QApplication::UnicodeUTF8));
        m_loopo2->setText(QApplication::translate("CProgramdistributionView", "2", 0, QApplication::UnicodeUTF8));
        m_loopo7->setText(QApplication::translate("CProgramdistributionView", "7", 0, QApplication::UnicodeUTF8));
        m_loopo6->setText(QApplication::translate("CProgramdistributionView", "6", 0, QApplication::UnicodeUTF8));
        m_loopo4->setText(QApplication::translate("CProgramdistributionView", "4", 0, QApplication::UnicodeUTF8));
        m_loopo1->setText(QApplication::translate("CProgramdistributionView", "1", 0, QApplication::UnicodeUTF8));
        removeLampLogin_button->setText(QApplication::translate("CProgramdistributionView", "\346\270\205\351\231\244\350\257\245\350\256\276\345\244\207\346\263\250\345\206\214\347\212\266\346\200\201", 0, QApplication::UnicodeUTF8));
        Q_UNUSED(CProgramdistributionView);
    } // retranslateUi

};

namespace Ui {
    class CProgramdistributionView: public Ui_CProgramdistributionView {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_CPROGRAMDISTRIBUTIONVIEW_H
