#ifndef OBJECTSTATUSENUM_H
#define OBJECTSTATUSENUM_H

#define OBJECT_STATUS_MAX 10000

enum ObjectStatus {
    OBJS_None = 0,
    OBJS_Start = 1,
    OBJS_Fault = 2,
    OBJS_Emergency = 3,
    OBJS_Fire = 4,
    OBJS_Online = 5,
    OBJS_LoginDeviceType = 6,
    OBJS_PowerChargerValue = 7,
    OBJS_PowerAutoValue = 8,
    OBJS_AutoEvacuation = 9,
    OBJS_InputPort = 10,
    OBJS_OutputPort = 11,
    OBJS_NewRegister = 12,
//Start:
    OBJS_PathStart = 13,
    OBJS_EvacuationGroupStart = 14,
    OBJS_UpStart = 15,
    OBJS_DownStart = 16,
    OBJS_LeftStart = 17,
    OBJS_RightStart = 18,
    OBJS_LightStart = 19,
//Fault:
    OBJS_SystemFault = 20,
    OBJS_PowerFault = 21,
    OBJS_MainPowerFault = 22,
    OBJS_StandbyPowerFault = 23,
    OBJS_ConcenterPowerFault = 24,
    OBJS_ChargerFault = 25,
    OBJS_PowerOutputFault = 26,
    OBJS_BatteryLineFault = 27,
    OBJS_BatteryLineFault_1 = 28,
    OBJS_BatteryLineFault_2 = 29,
    OBJS_BatteryLineFault_3 = 30,
    OBJS_BatteryLowVoltageFault = 31,
    OBJS_BatteryLowVoltageFault_1 = 32,
    OBJS_BatteryLowVoltageFault_2 = 33,
    OBJS_BatteryLowVoltageFault_3 = 34,
    OBJS_BatteryLowQuantityFault = 35,
    OBJS_BatteryOverDischargeFault = 36,
    OBJS_LoopOutShortFault = 37,
    OBJS_LoopOutOverloadFault = 38,
    OBJS_LoopCommunicationFault = 39,
    OBJS_NetCommunicationFault = 40,
    OBJS_LightCommunicationFault = 41,
    OBJS_LightFault = 42,
    OBJS_CheckFault = 43,
    OBJS_OutLoopFault = 44,
    OBJS_DistributionFault = 45,
    OBJS_DistributionCommunicationFault = 46,
    OBJS_PowerCommunicationFault = 47,
    OBJS_FASCommunicationFault = 48,
    OBJS_BatteryOffFault = 69,
    OBJS_BatteryShortFault = 70,
    OBJS_DeviceBatteryShortFault = 71,
    OBJS_DeviceBatteryOffFault = 72,
    OBJS_DeviceBatteryOverdischargeFault = 73,
    OBJS_StandbyPowerOff = 74,
    OBJS_StandbyPowerShort = 75,
    OBJS_StandbyPowerUndervoltage = 76,
//Emergency:
    OBJS_RemoteEmergency = 49,
    OBJS_FireEmergency = 50,
    OBJS_ForceEmergency = 51,
    OBJS_InputEmergency = 52,
    OBJS_ManualEmergency = 60,
    OBJS_DIEmergency = 64,
    OBJS_TestEmergency = 65,
    OBJS_SystemEmergency = 66,
    OBJS_UndervoltageEmergency = 67,
    OBJS_AutoEmergency = 68,
    OBJS_MonthEmergency = 69,
    OBJS_YearEmergency = 70,
    OBJS_SimulateFireEmergency = 77,
    OBJS_UnknownFireEmergency = 78,
//Other:
    OBJS_Mute = 53,
    OBJS_FirstFire = 54,
    OBJS_MainPowerWork = 55,
    OBJS_StandbyPowerWork = 56,
    OBJS_DirectionFlash = 57,
    OBJS_PowerKaiLuFault = 58,
    OBJS_PowerOutShortFault = 59,
    OBJS_RunMode = 61,
    OBJS_BatteryOverheating = 62,
    OBJS_ChargeStatus = 63,
};

#endif // OBJECTSTATUSENUM_H
