/********************************************************************************
** Form generated from reading UI file 'cprogramcandeviceview.ui'
**
** Created by: Qt User Interface Compiler version 4.8.7
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_CPROGRAMCANDEVICEVIEW_H
#define UI_CPROGRAMCANDEVICEVIEW_H

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtGui/QApplication>
#include <QtGui/QButtonGroup>
#include <QtGui/QGroupBox>
#include <QtGui/QHeaderView>
#include <QtGui/QLabel>
#include <QtGui/QTableView>
#include <QtGui/QWidget>

QT_BEGIN_NAMESPACE

class Ui_CProgramCanDeviceView
{
public:
    QLabel *label_mainpower;
    QLabel *m_mainpower;
    QLabel *m_backuppower;
    QLabel *label_backuppower;
    QLabel *label_openload;
    QLabel *m_overload;
    QLabel *m_openload;
    QLabel *label_overload;
    QLabel *m_systemfault;
    QLabel *label_emergency;
    QLabel *label_systemfault;
    QLabel *m_chargestatus;
    QLabel *m_emergency;
    QLabel *m_out36v;
    QLabel *label_out36v;
    QLabel *label_chargestatus;
    QLabel *m_undervoltage;
    QLabel *m_overdischarge;
    QLabel *m_overheat;
    QLabel *label_overdischarge;
    QLabel *m_runmode;
    QLabel *label_undervoltage;
    QLabel *label_overheat;
    QLabel *label_runmodel;
    QLabel *m_battery1V;
    QLabel *label_mainpowerV;
    QLabel *label_battery1T;
    QLabel *label_battery3V;
    QLabel *label_lightV;
    QLabel *m_lightV;
    QLabel *label_battery1V;
    QLabel *label_batteryV;
    QLabel *m_battery3V;
    QLabel *label_battery2V;
    QLabel *m_battery3T;
    QLabel *label_battery3T;
    QLabel *m_battery2T;
    QLabel *label_outpowerA;
    QLabel *m_battery2V;
    QLabel *m_outpowerA;
    QLabel *label_battery2T;
    QLabel *m_battery1T;
    QLabel *label_outpowerV;
    QLabel *m_outpowerV;
    QLabel *m_mainpowerV;
    QLabel *m_batteryV;
    QTableView *tableView;
    QGroupBox *groupBox_com;
    QLabel *m_loopc8;
    QLabel *m_loopc2;
    QLabel *m_loopc6;
    QLabel *m_loopc7;
    QLabel *m_loopc1;
    QLabel *m_loopc5;
    QLabel *m_loopc3;
    QLabel *m_loopc4;
    QGroupBox *groupBox_loopopen;
    QLabel *m_loopo8;
    QLabel *m_loopo6;
    QLabel *m_loopo4;
    QLabel *m_loopo1;
    QLabel *m_loopo5;
    QLabel *m_loopo3;
    QLabel *m_loopo2;
    QLabel *m_loopo7;
    QGroupBox *groupBox_loopV;
    QLabel *m_loop1V;
    QLabel *m_loop4V;
    QLabel *m_loop2V;
    QLabel *m_loop8V;
    QLabel *m_loop6V;
    QLabel *m_loop3V;
    QLabel *m_loop7V;
    QLabel *m_loop5V;
    QGroupBox *groupBox;
    QLabel *m_loop3A;
    QLabel *m_loop4A;
    QLabel *m_loop2A;
    QLabel *m_loop6A;
    QLabel *m_loop5A;
    QLabel *m_loop7A;
    QLabel *m_loop1A;
    QLabel *m_loop8A;
    QLabel *label_CPU;
    QLabel *label_CPUnumber;
    QLabel *label_POW;
    QLabel *label_POWnumber;
    QLabel *label_LCD;
    QLabel *label_LCDnumber;
    QLabel *label_ABUS1;
    QLabel *label_ABUS1number;
    QLabel *label_ABUS2;
    QLabel *label_ABUS2number;
    QLabel *label_ABUS6number;
    QLabel *label_ABUS4;
    QLabel *label_ABUS5number;
    QLabel *label_ABUS5;
    QLabel *label_ABUS6;
    QLabel *label_ABUS7number;
    QLabel *label_ABUS3;
    QLabel *label_ABUS4number;
    QLabel *label_ABUS7;
    QLabel *label_ABUS3number;
    QLabel *label_ABUS8;
    QLabel *label_ABUS8number;

    void setupUi(QWidget *CProgramCanDeviceView)
    {
        if (CProgramCanDeviceView->objectName().isEmpty())
            CProgramCanDeviceView->setObjectName(QString::fromUtf8("CProgramCanDeviceView"));
        CProgramCanDeviceView->resize(1366, 511);
        CProgramCanDeviceView->setMinimumSize(QSize(800, 200));
        CProgramCanDeviceView->setMaximumSize(QSize(1366, 661));
        QFont font;
        font.setPointSize(12);
        CProgramCanDeviceView->setFont(font);
        CProgramCanDeviceView->setContextMenuPolicy(Qt::DefaultContextMenu);
        CProgramCanDeviceView->setWindowTitle(QString::fromUtf8("Form"));
        CProgramCanDeviceView->setLayoutDirection(Qt::LeftToRight);
        label_mainpower = new QLabel(CProgramCanDeviceView);
        label_mainpower->setObjectName(QString::fromUtf8("label_mainpower"));
        label_mainpower->setGeometry(QRect(875, 10, 75, 25));
        label_mainpower->setFont(font);
        label_mainpower->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        m_mainpower = new QLabel(CProgramCanDeviceView);
        m_mainpower->setObjectName(QString::fromUtf8("m_mainpower"));
        m_mainpower->setGeometry(QRect(960, 10, 50, 25));
        m_mainpower->setFont(font);
        m_mainpower->setStyleSheet(QString::fromUtf8("background-color: rgb(0,255,0);"));
        m_mainpower->setAlignment(Qt::AlignCenter);
        m_backuppower = new QLabel(CProgramCanDeviceView);
        m_backuppower->setObjectName(QString::fromUtf8("m_backuppower"));
        m_backuppower->setGeometry(QRect(1115, 10, 50, 25));
        m_backuppower->setFont(font);
        m_backuppower->setStyleSheet(QString::fromUtf8("background-color: rgb(0,255,0);"));
        m_backuppower->setAlignment(Qt::AlignCenter);
        label_backuppower = new QLabel(CProgramCanDeviceView);
        label_backuppower->setObjectName(QString::fromUtf8("label_backuppower"));
        label_backuppower->setGeometry(QRect(1030, 10, 75, 25));
        label_backuppower->setFont(font);
        label_backuppower->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_openload = new QLabel(CProgramCanDeviceView);
        label_openload->setObjectName(QString::fromUtf8("label_openload"));
        label_openload->setGeometry(QRect(1030, 80, 75, 25));
        label_openload->setFont(font);
        label_openload->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        m_overload = new QLabel(CProgramCanDeviceView);
        m_overload->setObjectName(QString::fromUtf8("m_overload"));
        m_overload->setGeometry(QRect(960, 80, 50, 25));
        m_overload->setFont(font);
        m_overload->setStyleSheet(QString::fromUtf8("background-color: rgb(0,255,0);"));
        m_overload->setAlignment(Qt::AlignCenter);
        m_openload = new QLabel(CProgramCanDeviceView);
        m_openload->setObjectName(QString::fromUtf8("m_openload"));
        m_openload->setGeometry(QRect(1115, 80, 50, 25));
        m_openload->setFont(font);
        m_openload->setStyleSheet(QString::fromUtf8("background-color: rgb(0,255,0);"));
        m_openload->setAlignment(Qt::AlignCenter);
        label_overload = new QLabel(CProgramCanDeviceView);
        label_overload->setObjectName(QString::fromUtf8("label_overload"));
        label_overload->setGeometry(QRect(875, 80, 75, 25));
        label_overload->setFont(font);
        label_overload->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        m_systemfault = new QLabel(CProgramCanDeviceView);
        m_systemfault->setObjectName(QString::fromUtf8("m_systemfault"));
        m_systemfault->setGeometry(QRect(1270, 80, 50, 25));
        m_systemfault->setFont(font);
        m_systemfault->setStyleSheet(QString::fromUtf8("background-color: rgb(0,255,0);"));
        m_systemfault->setAlignment(Qt::AlignCenter);
        label_emergency = new QLabel(CProgramCanDeviceView);
        label_emergency->setObjectName(QString::fromUtf8("label_emergency"));
        label_emergency->setGeometry(QRect(1030, 45, 75, 25));
        label_emergency->setFont(font);
        label_emergency->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_systemfault = new QLabel(CProgramCanDeviceView);
        label_systemfault->setObjectName(QString::fromUtf8("label_systemfault"));
        label_systemfault->setGeometry(QRect(1185, 80, 75, 25));
        label_systemfault->setFont(font);
        label_systemfault->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        m_chargestatus = new QLabel(CProgramCanDeviceView);
        m_chargestatus->setObjectName(QString::fromUtf8("m_chargestatus"));
        m_chargestatus->setGeometry(QRect(1270, 45, 50, 25));
        m_chargestatus->setFont(font);
        m_chargestatus->setStyleSheet(QString::fromUtf8("background-color: rgb(0,255,0);"));
        m_chargestatus->setAlignment(Qt::AlignCenter);
        m_emergency = new QLabel(CProgramCanDeviceView);
        m_emergency->setObjectName(QString::fromUtf8("m_emergency"));
        m_emergency->setGeometry(QRect(1115, 45, 50, 25));
        m_emergency->setFont(font);
        m_emergency->setStyleSheet(QString::fromUtf8("background-color: rgb(0,255,0);"));
        m_emergency->setAlignment(Qt::AlignCenter);
        m_out36v = new QLabel(CProgramCanDeviceView);
        m_out36v->setObjectName(QString::fromUtf8("m_out36v"));
        m_out36v->setGeometry(QRect(960, 45, 50, 25));
        m_out36v->setFont(font);
        m_out36v->setStyleSheet(QString::fromUtf8("background-color: rgb(0,255,0);"));
        m_out36v->setAlignment(Qt::AlignCenter);
        label_out36v = new QLabel(CProgramCanDeviceView);
        label_out36v->setObjectName(QString::fromUtf8("label_out36v"));
        label_out36v->setGeometry(QRect(875, 45, 75, 25));
        label_out36v->setFont(font);
        label_out36v->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_chargestatus = new QLabel(CProgramCanDeviceView);
        label_chargestatus->setObjectName(QString::fromUtf8("label_chargestatus"));
        label_chargestatus->setGeometry(QRect(1185, 45, 75, 25));
        label_chargestatus->setFont(font);
        label_chargestatus->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        m_undervoltage = new QLabel(CProgramCanDeviceView);
        m_undervoltage->setObjectName(QString::fromUtf8("m_undervoltage"));
        m_undervoltage->setGeometry(QRect(960, 115, 50, 25));
        m_undervoltage->setFont(font);
        m_undervoltage->setStyleSheet(QString::fromUtf8("background-color: rgb(0,255,0);"));
        m_undervoltage->setAlignment(Qt::AlignCenter);
        m_overdischarge = new QLabel(CProgramCanDeviceView);
        m_overdischarge->setObjectName(QString::fromUtf8("m_overdischarge"));
        m_overdischarge->setGeometry(QRect(1270, 10, 50, 25));
        m_overdischarge->setFont(font);
        m_overdischarge->setStyleSheet(QString::fromUtf8("background-color: rgb(0,255,0);"));
        m_overdischarge->setAlignment(Qt::AlignCenter);
        m_overheat = new QLabel(CProgramCanDeviceView);
        m_overheat->setObjectName(QString::fromUtf8("m_overheat"));
        m_overheat->setGeometry(QRect(1115, 115, 50, 25));
        m_overheat->setFont(font);
        m_overheat->setStyleSheet(QString::fromUtf8("background-color: rgb(0,255,0);"));
        m_overheat->setAlignment(Qt::AlignCenter);
        label_overdischarge = new QLabel(CProgramCanDeviceView);
        label_overdischarge->setObjectName(QString::fromUtf8("label_overdischarge"));
        label_overdischarge->setGeometry(QRect(1185, 10, 75, 25));
        label_overdischarge->setFont(font);
        label_overdischarge->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        m_runmode = new QLabel(CProgramCanDeviceView);
        m_runmode->setObjectName(QString::fromUtf8("m_runmode"));
        m_runmode->setGeometry(QRect(1270, 115, 50, 25));
        m_runmode->setFont(font);
        m_runmode->setStyleSheet(QString::fromUtf8("background-color: rgb(0,255,0);"));
        m_runmode->setAlignment(Qt::AlignCenter);
        label_undervoltage = new QLabel(CProgramCanDeviceView);
        label_undervoltage->setObjectName(QString::fromUtf8("label_undervoltage"));
        label_undervoltage->setGeometry(QRect(875, 115, 75, 25));
        label_undervoltage->setFont(font);
        label_undervoltage->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_overheat = new QLabel(CProgramCanDeviceView);
        label_overheat->setObjectName(QString::fromUtf8("label_overheat"));
        label_overheat->setGeometry(QRect(1030, 115, 75, 25));
        label_overheat->setFont(font);
        label_overheat->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_runmodel = new QLabel(CProgramCanDeviceView);
        label_runmodel->setObjectName(QString::fromUtf8("label_runmodel"));
        label_runmodel->setGeometry(QRect(1185, 115, 75, 25));
        label_runmodel->setFont(font);
        label_runmodel->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        m_battery1V = new QLabel(CProgramCanDeviceView);
        m_battery1V->setObjectName(QString::fromUtf8("m_battery1V"));
        m_battery1V->setGeometry(QRect(960, 220, 50, 25));
        m_battery1V->setFont(font);
        m_battery1V->setAlignment(Qt::AlignCenter);
        label_mainpowerV = new QLabel(CProgramCanDeviceView);
        label_mainpowerV->setObjectName(QString::fromUtf8("label_mainpowerV"));
        label_mainpowerV->setGeometry(QRect(875, 150, 80, 25));
        label_mainpowerV->setFont(font);
        label_mainpowerV->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_battery1T = new QLabel(CProgramCanDeviceView);
        label_battery1T->setObjectName(QString::fromUtf8("label_battery1T"));
        label_battery1T->setGeometry(QRect(875, 255, 80, 25));
        label_battery1T->setFont(font);
        label_battery1T->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_battery3V = new QLabel(CProgramCanDeviceView);
        label_battery3V->setObjectName(QString::fromUtf8("label_battery3V"));
        label_battery3V->setGeometry(QRect(1185, 220, 80, 25));
        label_battery3V->setFont(font);
        label_battery3V->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_lightV = new QLabel(CProgramCanDeviceView);
        label_lightV->setObjectName(QString::fromUtf8("label_lightV"));
        label_lightV->setGeometry(QRect(875, 185, 80, 25));
        label_lightV->setFont(font);
        label_lightV->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        m_lightV = new QLabel(CProgramCanDeviceView);
        m_lightV->setObjectName(QString::fromUtf8("m_lightV"));
        m_lightV->setGeometry(QRect(960, 185, 50, 25));
        m_lightV->setFont(font);
        m_lightV->setAlignment(Qt::AlignCenter);
        label_battery1V = new QLabel(CProgramCanDeviceView);
        label_battery1V->setObjectName(QString::fromUtf8("label_battery1V"));
        label_battery1V->setGeometry(QRect(875, 220, 80, 25));
        label_battery1V->setFont(font);
        label_battery1V->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_batteryV = new QLabel(CProgramCanDeviceView);
        label_batteryV->setObjectName(QString::fromUtf8("label_batteryV"));
        label_batteryV->setGeometry(QRect(1030, 185, 80, 25));
        label_batteryV->setFont(font);
        label_batteryV->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        m_battery3V = new QLabel(CProgramCanDeviceView);
        m_battery3V->setObjectName(QString::fromUtf8("m_battery3V"));
        m_battery3V->setGeometry(QRect(1270, 220, 50, 25));
        m_battery3V->setFont(font);
        m_battery3V->setAlignment(Qt::AlignCenter);
        label_battery2V = new QLabel(CProgramCanDeviceView);
        label_battery2V->setObjectName(QString::fromUtf8("label_battery2V"));
        label_battery2V->setGeometry(QRect(1030, 220, 80, 25));
        label_battery2V->setFont(font);
        label_battery2V->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        m_battery3T = new QLabel(CProgramCanDeviceView);
        m_battery3T->setObjectName(QString::fromUtf8("m_battery3T"));
        m_battery3T->setGeometry(QRect(1270, 255, 50, 25));
        m_battery3T->setFont(font);
        m_battery3T->setAlignment(Qt::AlignCenter);
        label_battery3T = new QLabel(CProgramCanDeviceView);
        label_battery3T->setObjectName(QString::fromUtf8("label_battery3T"));
        label_battery3T->setGeometry(QRect(1185, 255, 80, 25));
        label_battery3T->setFont(font);
        label_battery3T->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        m_battery2T = new QLabel(CProgramCanDeviceView);
        m_battery2T->setObjectName(QString::fromUtf8("m_battery2T"));
        m_battery2T->setGeometry(QRect(1115, 255, 50, 25));
        m_battery2T->setFont(font);
        m_battery2T->setAlignment(Qt::AlignCenter);
        label_outpowerA = new QLabel(CProgramCanDeviceView);
        label_outpowerA->setObjectName(QString::fromUtf8("label_outpowerA"));
        label_outpowerA->setGeometry(QRect(1185, 150, 80, 25));
        label_outpowerA->setFont(font);
        label_outpowerA->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        m_battery2V = new QLabel(CProgramCanDeviceView);
        m_battery2V->setObjectName(QString::fromUtf8("m_battery2V"));
        m_battery2V->setGeometry(QRect(1115, 220, 50, 25));
        m_battery2V->setFont(font);
        m_battery2V->setAlignment(Qt::AlignCenter);
        m_outpowerA = new QLabel(CProgramCanDeviceView);
        m_outpowerA->setObjectName(QString::fromUtf8("m_outpowerA"));
        m_outpowerA->setGeometry(QRect(1270, 150, 50, 25));
        m_outpowerA->setFont(font);
        m_outpowerA->setAlignment(Qt::AlignCenter);
        label_battery2T = new QLabel(CProgramCanDeviceView);
        label_battery2T->setObjectName(QString::fromUtf8("label_battery2T"));
        label_battery2T->setGeometry(QRect(1030, 255, 80, 25));
        label_battery2T->setFont(font);
        label_battery2T->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        m_battery1T = new QLabel(CProgramCanDeviceView);
        m_battery1T->setObjectName(QString::fromUtf8("m_battery1T"));
        m_battery1T->setGeometry(QRect(960, 255, 50, 25));
        m_battery1T->setFont(font);
        m_battery1T->setAlignment(Qt::AlignCenter);
        label_outpowerV = new QLabel(CProgramCanDeviceView);
        label_outpowerV->setObjectName(QString::fromUtf8("label_outpowerV"));
        label_outpowerV->setGeometry(QRect(1030, 150, 80, 25));
        label_outpowerV->setFont(font);
        label_outpowerV->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        m_outpowerV = new QLabel(CProgramCanDeviceView);
        m_outpowerV->setObjectName(QString::fromUtf8("m_outpowerV"));
        m_outpowerV->setGeometry(QRect(1115, 150, 50, 25));
        m_outpowerV->setFont(font);
        m_outpowerV->setAlignment(Qt::AlignCenter);
        m_mainpowerV = new QLabel(CProgramCanDeviceView);
        m_mainpowerV->setObjectName(QString::fromUtf8("m_mainpowerV"));
        m_mainpowerV->setGeometry(QRect(960, 150, 50, 25));
        m_mainpowerV->setFont(font);
        m_mainpowerV->setAlignment(Qt::AlignCenter);
        m_batteryV = new QLabel(CProgramCanDeviceView);
        m_batteryV->setObjectName(QString::fromUtf8("m_batteryV"));
        m_batteryV->setGeometry(QRect(1115, 185, 50, 25));
        m_batteryV->setFont(font);
        m_batteryV->setAlignment(Qt::AlignCenter);
        tableView = new QTableView(CProgramCanDeviceView);
        tableView->setObjectName(QString::fromUtf8("tableView"));
        tableView->setGeometry(QRect(10, 10, 830, 390));
        tableView->setFont(font);
        groupBox_com = new QGroupBox(CProgramCanDeviceView);
        groupBox_com->setObjectName(QString::fromUtf8("groupBox_com"));
        groupBox_com->setGeometry(QRect(875, 285, 231, 90));
        groupBox_com->setFont(font);
        m_loopc8 = new QLabel(groupBox_com);
        m_loopc8->setObjectName(QString::fromUtf8("m_loopc8"));
        m_loopc8->setGeometry(QRect(175, 60, 40, 20));
        m_loopc8->setFont(font);
        m_loopc8->setLayoutDirection(Qt::LeftToRight);
        m_loopc8->setStyleSheet(QString::fromUtf8("background-color: rgb(0,255,0);"));
        m_loopc8->setAlignment(Qt::AlignCenter);
        m_loopc2 = new QLabel(groupBox_com);
        m_loopc2->setObjectName(QString::fromUtf8("m_loopc2"));
        m_loopc2->setGeometry(QRect(65, 30, 40, 20));
        m_loopc2->setFont(font);
        m_loopc2->setLayoutDirection(Qt::LeftToRight);
        m_loopc2->setStyleSheet(QString::fromUtf8("background-color: rgb(0,255,0);"));
        m_loopc2->setAlignment(Qt::AlignCenter);
        m_loopc6 = new QLabel(groupBox_com);
        m_loopc6->setObjectName(QString::fromUtf8("m_loopc6"));
        m_loopc6->setGeometry(QRect(65, 60, 40, 20));
        m_loopc6->setFont(font);
        m_loopc6->setLayoutDirection(Qt::LeftToRight);
        m_loopc6->setStyleSheet(QString::fromUtf8("background-color: rgb(0,255,0);"));
        m_loopc6->setAlignment(Qt::AlignCenter);
        m_loopc7 = new QLabel(groupBox_com);
        m_loopc7->setObjectName(QString::fromUtf8("m_loopc7"));
        m_loopc7->setGeometry(QRect(120, 60, 40, 20));
        m_loopc7->setFont(font);
        m_loopc7->setLayoutDirection(Qt::LeftToRight);
        m_loopc7->setStyleSheet(QString::fromUtf8("background-color: rgb(0,255,0);"));
        m_loopc7->setAlignment(Qt::AlignCenter);
        m_loopc1 = new QLabel(groupBox_com);
        m_loopc1->setObjectName(QString::fromUtf8("m_loopc1"));
        m_loopc1->setGeometry(QRect(10, 30, 40, 20));
        m_loopc1->setFont(font);
        m_loopc1->setLayoutDirection(Qt::LeftToRight);
        m_loopc1->setStyleSheet(QString::fromUtf8("background-color: rgb(0,255,0);"));
        m_loopc1->setAlignment(Qt::AlignCenter);
        m_loopc5 = new QLabel(groupBox_com);
        m_loopc5->setObjectName(QString::fromUtf8("m_loopc5"));
        m_loopc5->setGeometry(QRect(10, 60, 40, 20));
        m_loopc5->setFont(font);
        m_loopc5->setLayoutDirection(Qt::LeftToRight);
        m_loopc5->setStyleSheet(QString::fromUtf8("background-color: rgb(0,255,0);"));
        m_loopc5->setAlignment(Qt::AlignCenter);
        m_loopc3 = new QLabel(groupBox_com);
        m_loopc3->setObjectName(QString::fromUtf8("m_loopc3"));
        m_loopc3->setGeometry(QRect(120, 30, 40, 20));
        m_loopc3->setFont(font);
        m_loopc3->setLayoutDirection(Qt::LeftToRight);
        m_loopc3->setStyleSheet(QString::fromUtf8("background-color: rgb(0,255,0);"));
        m_loopc3->setAlignment(Qt::AlignCenter);
        m_loopc4 = new QLabel(groupBox_com);
        m_loopc4->setObjectName(QString::fromUtf8("m_loopc4"));
        m_loopc4->setGeometry(QRect(175, 30, 40, 20));
        m_loopc4->setFont(font);
        m_loopc4->setLayoutDirection(Qt::LeftToRight);
        m_loopc4->setStyleSheet(QString::fromUtf8("background-color: rgb(0,255,0);"));
        m_loopc4->setAlignment(Qt::AlignCenter);
        groupBox_loopopen = new QGroupBox(CProgramCanDeviceView);
        groupBox_loopopen->setObjectName(QString::fromUtf8("groupBox_loopopen"));
        groupBox_loopopen->setGeometry(QRect(1120, 285, 231, 90));
        groupBox_loopopen->setFont(font);
        m_loopo8 = new QLabel(groupBox_loopopen);
        m_loopo8->setObjectName(QString::fromUtf8("m_loopo8"));
        m_loopo8->setGeometry(QRect(175, 60, 40, 20));
        m_loopo8->setFont(font);
        m_loopo8->setLayoutDirection(Qt::LeftToRight);
        m_loopo8->setStyleSheet(QString::fromUtf8("background-color: rgb(0,255,0);"));
        m_loopo8->setAlignment(Qt::AlignCenter);
        m_loopo6 = new QLabel(groupBox_loopopen);
        m_loopo6->setObjectName(QString::fromUtf8("m_loopo6"));
        m_loopo6->setGeometry(QRect(65, 60, 40, 20));
        m_loopo6->setFont(font);
        m_loopo6->setLayoutDirection(Qt::LeftToRight);
        m_loopo6->setStyleSheet(QString::fromUtf8("background-color: rgb(0,255,0);"));
        m_loopo6->setAlignment(Qt::AlignCenter);
        m_loopo4 = new QLabel(groupBox_loopopen);
        m_loopo4->setObjectName(QString::fromUtf8("m_loopo4"));
        m_loopo4->setGeometry(QRect(175, 30, 40, 20));
        m_loopo4->setFont(font);
        m_loopo4->setLayoutDirection(Qt::LeftToRight);
        m_loopo4->setStyleSheet(QString::fromUtf8("background-color: rgb(0,255,0);"));
        m_loopo4->setAlignment(Qt::AlignCenter);
        m_loopo1 = new QLabel(groupBox_loopopen);
        m_loopo1->setObjectName(QString::fromUtf8("m_loopo1"));
        m_loopo1->setGeometry(QRect(10, 30, 40, 20));
        m_loopo1->setFont(font);
        m_loopo1->setLayoutDirection(Qt::LeftToRight);
        m_loopo1->setStyleSheet(QString::fromUtf8("background-color: rgb(0,255,0);"));
        m_loopo1->setAlignment(Qt::AlignCenter);
        m_loopo5 = new QLabel(groupBox_loopopen);
        m_loopo5->setObjectName(QString::fromUtf8("m_loopo5"));
        m_loopo5->setGeometry(QRect(10, 60, 40, 20));
        m_loopo5->setFont(font);
        m_loopo5->setLayoutDirection(Qt::LeftToRight);
        m_loopo5->setStyleSheet(QString::fromUtf8("background-color: rgb(0,255,0);"));
        m_loopo5->setAlignment(Qt::AlignCenter);
        m_loopo3 = new QLabel(groupBox_loopopen);
        m_loopo3->setObjectName(QString::fromUtf8("m_loopo3"));
        m_loopo3->setGeometry(QRect(120, 30, 40, 20));
        m_loopo3->setFont(font);
        m_loopo3->setLayoutDirection(Qt::LeftToRight);
        m_loopo3->setStyleSheet(QString::fromUtf8("background-color: rgb(0,255,0);"));
        m_loopo3->setAlignment(Qt::AlignCenter);
        m_loopo2 = new QLabel(groupBox_loopopen);
        m_loopo2->setObjectName(QString::fromUtf8("m_loopo2"));
        m_loopo2->setGeometry(QRect(65, 30, 40, 20));
        m_loopo2->setFont(font);
        m_loopo2->setLayoutDirection(Qt::LeftToRight);
        m_loopo2->setStyleSheet(QString::fromUtf8("background-color: rgb(0,255,0);"));
        m_loopo2->setAlignment(Qt::AlignCenter);
        m_loopo7 = new QLabel(groupBox_loopopen);
        m_loopo7->setObjectName(QString::fromUtf8("m_loopo7"));
        m_loopo7->setGeometry(QRect(120, 60, 40, 20));
        m_loopo7->setFont(font);
        m_loopo7->setLayoutDirection(Qt::LeftToRight);
        m_loopo7->setStyleSheet(QString::fromUtf8("background-color: rgb(0,255,0);"));
        m_loopo7->setAlignment(Qt::AlignCenter);
        groupBox_loopV = new QGroupBox(CProgramCanDeviceView);
        groupBox_loopV->setObjectName(QString::fromUtf8("groupBox_loopV"));
        groupBox_loopV->setGeometry(QRect(875, 380, 231, 90));
        groupBox_loopV->setFont(font);
        m_loop1V = new QLabel(groupBox_loopV);
        m_loop1V->setObjectName(QString::fromUtf8("m_loop1V"));
        m_loop1V->setGeometry(QRect(10, 30, 45, 20));
        m_loop1V->setFont(font);
        m_loop1V->setLayoutDirection(Qt::LeftToRight);
        m_loop1V->setAlignment(Qt::AlignCenter);
        m_loop4V = new QLabel(groupBox_loopV);
        m_loop4V->setObjectName(QString::fromUtf8("m_loop4V"));
        m_loop4V->setGeometry(QRect(175, 30, 45, 20));
        m_loop4V->setFont(font);
        m_loop4V->setLayoutDirection(Qt::LeftToRight);
        m_loop4V->setAlignment(Qt::AlignCenter);
        m_loop2V = new QLabel(groupBox_loopV);
        m_loop2V->setObjectName(QString::fromUtf8("m_loop2V"));
        m_loop2V->setGeometry(QRect(65, 30, 45, 20));
        m_loop2V->setFont(font);
        m_loop2V->setLayoutDirection(Qt::LeftToRight);
        m_loop2V->setAlignment(Qt::AlignCenter);
        m_loop8V = new QLabel(groupBox_loopV);
        m_loop8V->setObjectName(QString::fromUtf8("m_loop8V"));
        m_loop8V->setGeometry(QRect(175, 60, 45, 20));
        m_loop8V->setFont(font);
        m_loop8V->setLayoutDirection(Qt::LeftToRight);
        m_loop8V->setAlignment(Qt::AlignCenter);
        m_loop6V = new QLabel(groupBox_loopV);
        m_loop6V->setObjectName(QString::fromUtf8("m_loop6V"));
        m_loop6V->setGeometry(QRect(65, 60, 45, 20));
        m_loop6V->setFont(font);
        m_loop6V->setLayoutDirection(Qt::LeftToRight);
        m_loop6V->setAlignment(Qt::AlignCenter);
        m_loop3V = new QLabel(groupBox_loopV);
        m_loop3V->setObjectName(QString::fromUtf8("m_loop3V"));
        m_loop3V->setGeometry(QRect(120, 30, 45, 20));
        m_loop3V->setFont(font);
        m_loop3V->setLayoutDirection(Qt::LeftToRight);
        m_loop3V->setAlignment(Qt::AlignCenter);
        m_loop7V = new QLabel(groupBox_loopV);
        m_loop7V->setObjectName(QString::fromUtf8("m_loop7V"));
        m_loop7V->setGeometry(QRect(120, 60, 45, 20));
        m_loop7V->setFont(font);
        m_loop7V->setLayoutDirection(Qt::LeftToRight);
        m_loop7V->setAlignment(Qt::AlignCenter);
        m_loop5V = new QLabel(groupBox_loopV);
        m_loop5V->setObjectName(QString::fromUtf8("m_loop5V"));
        m_loop5V->setGeometry(QRect(10, 60, 45, 20));
        m_loop5V->setFont(font);
        m_loop5V->setLayoutDirection(Qt::LeftToRight);
        m_loop5V->setAlignment(Qt::AlignCenter);
        groupBox = new QGroupBox(CProgramCanDeviceView);
        groupBox->setObjectName(QString::fromUtf8("groupBox"));
        groupBox->setGeometry(QRect(1120, 380, 231, 90));
        groupBox->setFont(font);
        m_loop3A = new QLabel(groupBox);
        m_loop3A->setObjectName(QString::fromUtf8("m_loop3A"));
        m_loop3A->setGeometry(QRect(120, 30, 45, 20));
        m_loop3A->setFont(font);
        m_loop3A->setLayoutDirection(Qt::LeftToRight);
        m_loop3A->setAlignment(Qt::AlignCenter);
        m_loop4A = new QLabel(groupBox);
        m_loop4A->setObjectName(QString::fromUtf8("m_loop4A"));
        m_loop4A->setGeometry(QRect(175, 30, 45, 20));
        m_loop4A->setFont(font);
        m_loop4A->setLayoutDirection(Qt::LeftToRight);
        m_loop4A->setAlignment(Qt::AlignCenter);
        m_loop2A = new QLabel(groupBox);
        m_loop2A->setObjectName(QString::fromUtf8("m_loop2A"));
        m_loop2A->setGeometry(QRect(65, 30, 45, 20));
        m_loop2A->setFont(font);
        m_loop2A->setLayoutDirection(Qt::LeftToRight);
        m_loop2A->setAlignment(Qt::AlignCenter);
        m_loop6A = new QLabel(groupBox);
        m_loop6A->setObjectName(QString::fromUtf8("m_loop6A"));
        m_loop6A->setGeometry(QRect(65, 60, 45, 20));
        m_loop6A->setFont(font);
        m_loop6A->setLayoutDirection(Qt::LeftToRight);
        m_loop6A->setAlignment(Qt::AlignCenter);
        m_loop5A = new QLabel(groupBox);
        m_loop5A->setObjectName(QString::fromUtf8("m_loop5A"));
        m_loop5A->setGeometry(QRect(10, 60, 45, 20));
        m_loop5A->setFont(font);
        m_loop5A->setLayoutDirection(Qt::LeftToRight);
        m_loop5A->setAlignment(Qt::AlignCenter);
        m_loop7A = new QLabel(groupBox);
        m_loop7A->setObjectName(QString::fromUtf8("m_loop7A"));
        m_loop7A->setGeometry(QRect(120, 60, 45, 20));
        m_loop7A->setFont(font);
        m_loop7A->setLayoutDirection(Qt::LeftToRight);
        m_loop7A->setAlignment(Qt::AlignCenter);
        m_loop1A = new QLabel(groupBox);
        m_loop1A->setObjectName(QString::fromUtf8("m_loop1A"));
        m_loop1A->setGeometry(QRect(10, 30, 45, 20));
        m_loop1A->setFont(font);
        m_loop1A->setLayoutDirection(Qt::LeftToRight);
        m_loop1A->setAlignment(Qt::AlignCenter);
        m_loop8A = new QLabel(groupBox);
        m_loop8A->setObjectName(QString::fromUtf8("m_loop8A"));
        m_loop8A->setGeometry(QRect(175, 60, 45, 20));
        m_loop8A->setFont(font);
        m_loop8A->setLayoutDirection(Qt::LeftToRight);
        m_loop8A->setAlignment(Qt::AlignCenter);
        label_CPU = new QLabel(CProgramCanDeviceView);
        label_CPU->setObjectName(QString::fromUtf8("label_CPU"));
        label_CPU->setGeometry(QRect(40, 410, 80, 25));
        label_CPU->setFont(font);
        label_CPUnumber = new QLabel(CProgramCanDeviceView);
        label_CPUnumber->setObjectName(QString::fromUtf8("label_CPUnumber"));
        label_CPUnumber->setGeometry(QRect(130, 410, 40, 25));
        label_CPUnumber->setFont(font);
        label_POW = new QLabel(CProgramCanDeviceView);
        label_POW->setObjectName(QString::fromUtf8("label_POW"));
        label_POW->setGeometry(QRect(170, 410, 80, 25));
        label_POW->setFont(font);
        label_POWnumber = new QLabel(CProgramCanDeviceView);
        label_POWnumber->setObjectName(QString::fromUtf8("label_POWnumber"));
        label_POWnumber->setGeometry(QRect(260, 410, 40, 25));
        label_POWnumber->setFont(font);
        label_LCD = new QLabel(CProgramCanDeviceView);
        label_LCD->setObjectName(QString::fromUtf8("label_LCD"));
        label_LCD->setGeometry(QRect(300, 410, 80, 25));
        label_LCD->setFont(font);
        label_LCDnumber = new QLabel(CProgramCanDeviceView);
        label_LCDnumber->setObjectName(QString::fromUtf8("label_LCDnumber"));
        label_LCDnumber->setGeometry(QRect(390, 410, 40, 25));
        label_LCDnumber->setFont(font);
        label_ABUS1 = new QLabel(CProgramCanDeviceView);
        label_ABUS1->setObjectName(QString::fromUtf8("label_ABUS1"));
        label_ABUS1->setGeometry(QRect(440, 410, 90, 25));
        label_ABUS1->setFont(font);
        label_ABUS1number = new QLabel(CProgramCanDeviceView);
        label_ABUS1number->setObjectName(QString::fromUtf8("label_ABUS1number"));
        label_ABUS1number->setGeometry(QRect(530, 410, 40, 25));
        label_ABUS1number->setFont(font);
        label_ABUS2 = new QLabel(CProgramCanDeviceView);
        label_ABUS2->setObjectName(QString::fromUtf8("label_ABUS2"));
        label_ABUS2->setGeometry(QRect(570, 410, 90, 25));
        label_ABUS2->setFont(font);
        label_ABUS2number = new QLabel(CProgramCanDeviceView);
        label_ABUS2number->setObjectName(QString::fromUtf8("label_ABUS2number"));
        label_ABUS2number->setGeometry(QRect(660, 410, 40, 25));
        label_ABUS2number->setFont(font);
        label_ABUS6number = new QLabel(CProgramCanDeviceView);
        label_ABUS6number->setObjectName(QString::fromUtf8("label_ABUS6number"));
        label_ABUS6number->setGeometry(QRect(390, 440, 40, 25));
        label_ABUS6number->setFont(font);
        label_ABUS4 = new QLabel(CProgramCanDeviceView);
        label_ABUS4->setObjectName(QString::fromUtf8("label_ABUS4"));
        label_ABUS4->setGeometry(QRect(40, 440, 90, 25));
        label_ABUS4->setFont(font);
        label_ABUS5number = new QLabel(CProgramCanDeviceView);
        label_ABUS5number->setObjectName(QString::fromUtf8("label_ABUS5number"));
        label_ABUS5number->setGeometry(QRect(260, 440, 40, 25));
        label_ABUS5number->setFont(font);
        label_ABUS5 = new QLabel(CProgramCanDeviceView);
        label_ABUS5->setObjectName(QString::fromUtf8("label_ABUS5"));
        label_ABUS5->setGeometry(QRect(170, 440, 90, 25));
        label_ABUS5->setFont(font);
        label_ABUS6 = new QLabel(CProgramCanDeviceView);
        label_ABUS6->setObjectName(QString::fromUtf8("label_ABUS6"));
        label_ABUS6->setGeometry(QRect(300, 440, 90, 25));
        label_ABUS6->setFont(font);
        label_ABUS7number = new QLabel(CProgramCanDeviceView);
        label_ABUS7number->setObjectName(QString::fromUtf8("label_ABUS7number"));
        label_ABUS7number->setGeometry(QRect(530, 440, 40, 25));
        label_ABUS7number->setFont(font);
        label_ABUS3 = new QLabel(CProgramCanDeviceView);
        label_ABUS3->setObjectName(QString::fromUtf8("label_ABUS3"));
        label_ABUS3->setGeometry(QRect(700, 410, 90, 25));
        label_ABUS3->setFont(font);
        label_ABUS4number = new QLabel(CProgramCanDeviceView);
        label_ABUS4number->setObjectName(QString::fromUtf8("label_ABUS4number"));
        label_ABUS4number->setGeometry(QRect(130, 440, 40, 25));
        label_ABUS4number->setFont(font);
        label_ABUS7 = new QLabel(CProgramCanDeviceView);
        label_ABUS7->setObjectName(QString::fromUtf8("label_ABUS7"));
        label_ABUS7->setGeometry(QRect(440, 440, 90, 25));
        label_ABUS7->setFont(font);
        label_ABUS3number = new QLabel(CProgramCanDeviceView);
        label_ABUS3number->setObjectName(QString::fromUtf8("label_ABUS3number"));
        label_ABUS3number->setGeometry(QRect(790, 410, 40, 25));
        label_ABUS3number->setFont(font);
        label_ABUS8 = new QLabel(CProgramCanDeviceView);
        label_ABUS8->setObjectName(QString::fromUtf8("label_ABUS8"));
        label_ABUS8->setGeometry(QRect(570, 440, 90, 25));
        label_ABUS8->setFont(font);
        label_ABUS8number = new QLabel(CProgramCanDeviceView);
        label_ABUS8number->setObjectName(QString::fromUtf8("label_ABUS8number"));
        label_ABUS8number->setGeometry(QRect(660, 440, 40, 25));
        label_ABUS8number->setFont(font);

        retranslateUi(CProgramCanDeviceView);

        QMetaObject::connectSlotsByName(CProgramCanDeviceView);
    } // setupUi

    void retranslateUi(QWidget *CProgramCanDeviceView)
    {
        label_mainpower->setText(QApplication::translate("CProgramCanDeviceView", "\344\270\273\347\224\265:", 0, QApplication::UnicodeUTF8));
        m_mainpower->setText(QApplication::translate("CProgramCanDeviceView", "\346\255\243\345\270\270", 0, QApplication::UnicodeUTF8));
        m_backuppower->setText(QApplication::translate("CProgramCanDeviceView", "\346\255\243\345\270\270", 0, QApplication::UnicodeUTF8));
        label_backuppower->setText(QApplication::translate("CProgramCanDeviceView", "\345\244\207\347\224\265:", 0, QApplication::UnicodeUTF8));
        label_openload->setText(QApplication::translate("CProgramCanDeviceView", "\350\276\223\345\207\272\345\274\200\350\267\257:", 0, QApplication::UnicodeUTF8));
        m_overload->setText(QApplication::translate("CProgramCanDeviceView", "\346\255\243\345\270\270", 0, QApplication::UnicodeUTF8));
        m_openload->setText(QApplication::translate("CProgramCanDeviceView", "\346\255\243\345\270\270", 0, QApplication::UnicodeUTF8));
        label_overload->setText(QApplication::translate("CProgramCanDeviceView", "\350\276\223\345\207\272\350\277\207\350\275\275:", 0, QApplication::UnicodeUTF8));
        m_systemfault->setText(QApplication::translate("CProgramCanDeviceView", "\346\255\243\345\270\270", 0, QApplication::UnicodeUTF8));
        label_emergency->setText(QApplication::translate("CProgramCanDeviceView", "\345\272\224\346\200\245:", 0, QApplication::UnicodeUTF8));
        label_systemfault->setText(QApplication::translate("CProgramCanDeviceView", "\347\263\273\347\273\237\346\225\205\351\232\234:", 0, QApplication::UnicodeUTF8));
        m_chargestatus->setText(QApplication::translate("CProgramCanDeviceView", "\346\234\252\345\205\205\347\224\265", 0, QApplication::UnicodeUTF8));
        m_emergency->setText(QApplication::translate("CProgramCanDeviceView", "\346\255\243\345\270\270", 0, QApplication::UnicodeUTF8));
        m_out36v->setText(QApplication::translate("CProgramCanDeviceView", "\346\255\243\345\270\270", 0, QApplication::UnicodeUTF8));
        label_out36v->setText(QApplication::translate("CProgramCanDeviceView", "36V\350\276\223\345\207\272:", 0, QApplication::UnicodeUTF8));
        label_chargestatus->setText(QApplication::translate("CProgramCanDeviceView", "\345\205\205\347\224\265\347\212\266\346\200\201:", 0, QApplication::UnicodeUTF8));
        m_undervoltage->setText(QApplication::translate("CProgramCanDeviceView", "\346\255\243\345\270\270", 0, QApplication::UnicodeUTF8));
        m_overdischarge->setText(QApplication::translate("CProgramCanDeviceView", "\346\255\243\345\270\270", 0, QApplication::UnicodeUTF8));
        m_overheat->setText(QApplication::translate("CProgramCanDeviceView", "\346\255\243\345\270\270", 0, QApplication::UnicodeUTF8));
        label_overdischarge->setText(QApplication::translate("CProgramCanDeviceView", "\350\277\207\346\224\276\347\224\265:", 0, QApplication::UnicodeUTF8));
        m_runmode->setText(QApplication::translate("CProgramCanDeviceView", "\350\207\252\345\212\250", 0, QApplication::UnicodeUTF8));
        label_undervoltage->setText(QApplication::translate("CProgramCanDeviceView", "\347\224\265\346\261\240\346\254\240\345\216\213:", 0, QApplication::UnicodeUTF8));
        label_overheat->setText(QApplication::translate("CProgramCanDeviceView", "\347\224\265\346\261\240\350\277\207\347\203\255:", 0, QApplication::UnicodeUTF8));
        label_runmodel->setText(QApplication::translate("CProgramCanDeviceView", "\350\277\220\350\241\214\346\250\241\345\274\217:", 0, QApplication::UnicodeUTF8));
        m_battery1V->setText(QApplication::translate("CProgramCanDeviceView", "0V", 0, QApplication::UnicodeUTF8));
        label_mainpowerV->setText(QApplication::translate("CProgramCanDeviceView", "\344\270\273\347\224\265\347\224\265\345\216\213:", 0, QApplication::UnicodeUTF8));
        label_battery1T->setText(QApplication::translate("CProgramCanDeviceView", "\347\224\265\346\261\2401\346\270\251\345\272\246:", 0, QApplication::UnicodeUTF8));
        label_battery3V->setText(QApplication::translate("CProgramCanDeviceView", "\347\224\265\346\261\2403\347\224\265\345\216\213:", 0, QApplication::UnicodeUTF8));
        label_lightV->setText(QApplication::translate("CProgramCanDeviceView", "\345\244\226\351\203\250\347\224\265\345\216\213:", 0, QApplication::UnicodeUTF8));
        m_lightV->setText(QApplication::translate("CProgramCanDeviceView", "0V", 0, QApplication::UnicodeUTF8));
        label_battery1V->setText(QApplication::translate("CProgramCanDeviceView", "\347\224\265\346\261\2401\347\224\265\345\216\213:", 0, QApplication::UnicodeUTF8));
        label_batteryV->setText(QApplication::translate("CProgramCanDeviceView", "\347\224\265\346\261\240\346\200\273\347\224\265\345\216\213:", 0, QApplication::UnicodeUTF8));
        m_battery3V->setText(QApplication::translate("CProgramCanDeviceView", "0V", 0, QApplication::UnicodeUTF8));
        label_battery2V->setText(QApplication::translate("CProgramCanDeviceView", "\347\224\265\346\261\2402\347\224\265\345\216\213:", 0, QApplication::UnicodeUTF8));
        m_battery3T->setText(QApplication::translate("CProgramCanDeviceView", "0", 0, QApplication::UnicodeUTF8));
        label_battery3T->setText(QApplication::translate("CProgramCanDeviceView", "\347\224\265\346\261\2403\346\270\251\345\272\246:", 0, QApplication::UnicodeUTF8));
        m_battery2T->setText(QApplication::translate("CProgramCanDeviceView", "0", 0, QApplication::UnicodeUTF8));
        label_outpowerA->setText(QApplication::translate("CProgramCanDeviceView", "\350\276\223\345\207\272\347\224\265\346\265\201:", 0, QApplication::UnicodeUTF8));
        m_battery2V->setText(QApplication::translate("CProgramCanDeviceView", "0V", 0, QApplication::UnicodeUTF8));
        m_outpowerA->setText(QApplication::translate("CProgramCanDeviceView", "0A", 0, QApplication::UnicodeUTF8));
        label_battery2T->setText(QApplication::translate("CProgramCanDeviceView", "\347\224\265\346\261\2402\346\270\251\345\272\246:", 0, QApplication::UnicodeUTF8));
        m_battery1T->setText(QApplication::translate("CProgramCanDeviceView", "0", 0, QApplication::UnicodeUTF8));
        label_outpowerV->setText(QApplication::translate("CProgramCanDeviceView", "\350\276\223\345\207\272\347\224\265\345\216\213:", 0, QApplication::UnicodeUTF8));
        m_outpowerV->setText(QApplication::translate("CProgramCanDeviceView", "0V", 0, QApplication::UnicodeUTF8));
        m_mainpowerV->setText(QApplication::translate("CProgramCanDeviceView", "0V", 0, QApplication::UnicodeUTF8));
        m_batteryV->setText(QApplication::translate("CProgramCanDeviceView", "0V", 0, QApplication::UnicodeUTF8));
        groupBox_com->setTitle(QApplication::translate("CProgramCanDeviceView", "\345\233\236\350\267\257\351\200\232\350\256\257", 0, QApplication::UnicodeUTF8));
        m_loopc8->setText(QApplication::translate("CProgramCanDeviceView", "8", 0, QApplication::UnicodeUTF8));
        m_loopc2->setText(QApplication::translate("CProgramCanDeviceView", "2", 0, QApplication::UnicodeUTF8));
        m_loopc6->setText(QApplication::translate("CProgramCanDeviceView", "6", 0, QApplication::UnicodeUTF8));
        m_loopc7->setText(QApplication::translate("CProgramCanDeviceView", "7", 0, QApplication::UnicodeUTF8));
        m_loopc1->setText(QApplication::translate("CProgramCanDeviceView", "1", 0, QApplication::UnicodeUTF8));
        m_loopc5->setText(QApplication::translate("CProgramCanDeviceView", "5", 0, QApplication::UnicodeUTF8));
        m_loopc3->setText(QApplication::translate("CProgramCanDeviceView", "3", 0, QApplication::UnicodeUTF8));
        m_loopc4->setText(QApplication::translate("CProgramCanDeviceView", "4", 0, QApplication::UnicodeUTF8));
        groupBox_loopopen->setTitle(QApplication::translate("CProgramCanDeviceView", "\345\233\236\350\267\257\345\274\200\350\267\257", 0, QApplication::UnicodeUTF8));
        m_loopo8->setText(QApplication::translate("CProgramCanDeviceView", "8", 0, QApplication::UnicodeUTF8));
        m_loopo6->setText(QApplication::translate("CProgramCanDeviceView", "6", 0, QApplication::UnicodeUTF8));
        m_loopo4->setText(QApplication::translate("CProgramCanDeviceView", "4", 0, QApplication::UnicodeUTF8));
        m_loopo1->setText(QApplication::translate("CProgramCanDeviceView", "1", 0, QApplication::UnicodeUTF8));
        m_loopo5->setText(QApplication::translate("CProgramCanDeviceView", "5", 0, QApplication::UnicodeUTF8));
        m_loopo3->setText(QApplication::translate("CProgramCanDeviceView", "3", 0, QApplication::UnicodeUTF8));
        m_loopo2->setText(QApplication::translate("CProgramCanDeviceView", "2", 0, QApplication::UnicodeUTF8));
        m_loopo7->setText(QApplication::translate("CProgramCanDeviceView", "7", 0, QApplication::UnicodeUTF8));
        groupBox_loopV->setTitle(QApplication::translate("CProgramCanDeviceView", "\345\233\236\350\267\257\347\224\265\345\216\213", 0, QApplication::UnicodeUTF8));
        m_loop1V->setText(QApplication::translate("CProgramCanDeviceView", "0V", 0, QApplication::UnicodeUTF8));
        m_loop4V->setText(QApplication::translate("CProgramCanDeviceView", "0V", 0, QApplication::UnicodeUTF8));
        m_loop2V->setText(QApplication::translate("CProgramCanDeviceView", "0V", 0, QApplication::UnicodeUTF8));
        m_loop8V->setText(QApplication::translate("CProgramCanDeviceView", "0V", 0, QApplication::UnicodeUTF8));
        m_loop6V->setText(QApplication::translate("CProgramCanDeviceView", "0V", 0, QApplication::UnicodeUTF8));
        m_loop3V->setText(QApplication::translate("CProgramCanDeviceView", "0V", 0, QApplication::UnicodeUTF8));
        m_loop7V->setText(QApplication::translate("CProgramCanDeviceView", "0V", 0, QApplication::UnicodeUTF8));
        m_loop5V->setText(QApplication::translate("CProgramCanDeviceView", "0V", 0, QApplication::UnicodeUTF8));
        groupBox->setTitle(QApplication::translate("CProgramCanDeviceView", "\345\233\236\350\267\257\347\224\265\346\265\201", 0, QApplication::UnicodeUTF8));
        m_loop3A->setText(QApplication::translate("CProgramCanDeviceView", "0A", 0, QApplication::UnicodeUTF8));
        m_loop4A->setText(QApplication::translate("CProgramCanDeviceView", "0A", 0, QApplication::UnicodeUTF8));
        m_loop2A->setText(QApplication::translate("CProgramCanDeviceView", "0A", 0, QApplication::UnicodeUTF8));
        m_loop6A->setText(QApplication::translate("CProgramCanDeviceView", "0A", 0, QApplication::UnicodeUTF8));
        m_loop5A->setText(QApplication::translate("CProgramCanDeviceView", "0A", 0, QApplication::UnicodeUTF8));
        m_loop7A->setText(QApplication::translate("CProgramCanDeviceView", "0A", 0, QApplication::UnicodeUTF8));
        m_loop1A->setText(QApplication::translate("CProgramCanDeviceView", "0A", 0, QApplication::UnicodeUTF8));
        m_loop8A->setText(QApplication::translate("CProgramCanDeviceView", "0A", 0, QApplication::UnicodeUTF8));
        label_CPU->setText(QApplication::translate("CProgramCanDeviceView", "CPU\347\211\210\346\234\254:", 0, QApplication::UnicodeUTF8));
        label_CPUnumber->setText(QApplication::translate("CProgramCanDeviceView", "0", 0, QApplication::UnicodeUTF8));
        label_POW->setText(QApplication::translate("CProgramCanDeviceView", "POW\347\211\210\346\234\254:", 0, QApplication::UnicodeUTF8));
        label_POWnumber->setText(QApplication::translate("CProgramCanDeviceView", "0", 0, QApplication::UnicodeUTF8));
        label_LCD->setText(QApplication::translate("CProgramCanDeviceView", "LCD\347\211\210\346\234\254:", 0, QApplication::UnicodeUTF8));
        label_LCDnumber->setText(QApplication::translate("CProgramCanDeviceView", "0", 0, QApplication::UnicodeUTF8));
        label_ABUS1->setText(QApplication::translate("CProgramCanDeviceView", "ABUS1\347\211\210\346\234\254:", 0, QApplication::UnicodeUTF8));
        label_ABUS1number->setText(QApplication::translate("CProgramCanDeviceView", "0", 0, QApplication::UnicodeUTF8));
        label_ABUS2->setText(QApplication::translate("CProgramCanDeviceView", "ABUS2\347\211\210\346\234\254:", 0, QApplication::UnicodeUTF8));
        label_ABUS2number->setText(QApplication::translate("CProgramCanDeviceView", "0", 0, QApplication::UnicodeUTF8));
        label_ABUS6number->setText(QApplication::translate("CProgramCanDeviceView", "0", 0, QApplication::UnicodeUTF8));
        label_ABUS4->setText(QApplication::translate("CProgramCanDeviceView", "ABUS4\347\211\210\346\234\254:", 0, QApplication::UnicodeUTF8));
        label_ABUS5number->setText(QApplication::translate("CProgramCanDeviceView", "0", 0, QApplication::UnicodeUTF8));
        label_ABUS5->setText(QApplication::translate("CProgramCanDeviceView", "ABUS5\347\211\210\346\234\254:", 0, QApplication::UnicodeUTF8));
        label_ABUS6->setText(QApplication::translate("CProgramCanDeviceView", "ABUS6\347\211\210\346\234\254:", 0, QApplication::UnicodeUTF8));
        label_ABUS7number->setText(QApplication::translate("CProgramCanDeviceView", "0", 0, QApplication::UnicodeUTF8));
        label_ABUS3->setText(QApplication::translate("CProgramCanDeviceView", "ABUS3\347\211\210\346\234\254:", 0, QApplication::UnicodeUTF8));
        label_ABUS4number->setText(QApplication::translate("CProgramCanDeviceView", "0", 0, QApplication::UnicodeUTF8));
        label_ABUS7->setText(QApplication::translate("CProgramCanDeviceView", "ABUS7\347\211\210\346\234\254:", 0, QApplication::UnicodeUTF8));
        label_ABUS3number->setText(QApplication::translate("CProgramCanDeviceView", "0", 0, QApplication::UnicodeUTF8));
        label_ABUS8->setText(QApplication::translate("CProgramCanDeviceView", "ABUS8\347\211\210\346\234\254:", 0, QApplication::UnicodeUTF8));
        label_ABUS8number->setText(QApplication::translate("CProgramCanDeviceView", "0", 0, QApplication::UnicodeUTF8));
        Q_UNUSED(CProgramCanDeviceView);
    } // retranslateUi

};

namespace Ui {
    class CProgramCanDeviceView: public Ui_CProgramCanDeviceView {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_CPROGRAMCANDEVICEVIEW_H
